### ISSUE TITLE
Removed .project files from cartridges

### ISSUE THREAD

**Issue by aleksandar-kirilov-ewave** [Adyen/adyen-salesforce-commerce-cloud#1020]
Hello Adyen team, can someone explain the reason for removing `.project' files in version 23.1.1?
The problem this change causes is that it affects the most popular SFCC extension ([Prophet Debugger](https://github.com/SqrTT/prophet)) to detect and upload your cartridges.

**Comment by amihajlovski** [comment]
Hello @aleksandar-kirilov-ewave 

We haven't removed it intentionally, can you please refer in which version you had it last time? 
I cannot see it in most of the versions. 

Kind Regards
Aleksandar
Adyen

**Comment by aleksandar-kirilov-ewave** [comment]
Thanks for your reply @amihajlovski, looks like these files were removed in version 22.2.0 and I can see them in version 22.1.1

**Comment by zenit2001** [comment]
Hi @aleksandar-kirilov-ewave , 

We have added the `.project` files in the new release v24.1.0.

With kind regards,
Zenit
Adyen
