### ISSUE TITLE
Issues with 3DS2

### ISSUE THREAD

**Issue by amidongarrett** [Adyen/adyen-salesforce-commerce-cloud#1035]
**Describe the bug**
We are working on upgrading to 23.3.1 and have run into issues with the 3DS2 implementation. We are able to use the 3DS2 enabled test card and get to the challenge shopper page hosted by adyen, but on return we are seeing quite a few errors. 

1. "Params do not match route" error - from what I can see, Adyen is attempting to redirect back to Adyen-ShowConfirmation using POST, but the route is registered using GET
2. If I manually fix the above in int_adyen_SFRA, the next error we run into "Could not verify /payment/details: TypeError: Cannot read property "resultCode" from null in int_adyen_SFRA/cartridge/controllers/middlewares/adyen/showConfirmation.js:37" - Looking at this code:
`var detailsResult = getPaymentsDetailsResult(adyenPaymentInstrument, redirectResult, payload, req);
  return handlePaymentsDetailsResult(adyenPaymentInstrument, detailsResult, order, options);`

getPaymentsDetailsResult expects either redirectResult or payload to exist in the querystring when calling Adyen-ShowConfirmation. When debugging, the only data passed to us is signature, merchantReference and the orderToken. Since neither redirectResult or payload are present, the result from this method is null. Then when calling handlePaymentsDetailsResult, we get the error, as the code assumes that detailsResult is an object and attempts to access detailsResult.resultCode

**To Reproduce**
1. Go to checkout
2. Fill out steps prior to the payment steps and Continue
3. Use a card enabled with 3ds2 (we have been using 5454... from https://docs.adyen.com/development-resources/testing/test-card-numbers/#enrolled-in-3d-secure-2)
4. Continue and place the order
5. Redirect to 3DS2
6. Fill at the 3ds2 login information in the adyen checkout shopper page
7. Redirect back to system and see errors

**Expected behavior**
Customer completes the call to Adyen-ShowConfirmation and gets redirected to order confirmation if the payment was authorized

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOs Sonoma 
 - Browser: chrome
 - Version: 120.0.6099.129

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
Similar experience when using Maestro as well

**Comment by amihajlovski** [comment]
Hello @amidongarrett 

We again tested this flow on our latest version using the same card and I can confirm it works. 
Please try on a clean instance without any customizations. Closing this issue now and please open a new one if the problem still occurs.

Kind regards,
Aleksandar
Adyen
