### ISSUE TITLE
TransactionType is not correctly set to 'CAPTURE' for SALE payment methods from  AdyenSalePaymentMethods

### ISSUE THREAD

**Issue by georgi-il** [Adyen/adyen-salesforce-commerce-cloud#1067]
**Describe the bug**
TransactionType is not set correctly to 'CAPTURE' for SALE payment methods from  AdyenSalePaymentMethods

**To Reproduce**
1. set AdyenSalePaymentMethods site pref  to "paypal"
2. Place a PayPal order
3. Check the order afterwards - the paymentTransaction.type of the payment instrument doesn't have any value.

**Expected behavior**
The paymentTransaction.type should be "CAPTURE".

**Additional context**
The issue is in paymentFromComponent.js#160 - the payment method reference from the basket is passed to adyenCheckout.createPaymentRequest, but since the order has already been created, the payment instrument in the order is already a different object with a different UUID. So setting the paymentTransaction on the basket payment instrument has no effect.
This is the fix we use in our project:
![321543090-d66c695e-90d9-49be-9395-bd70949d0a6c](https://github.com/Adyen/adyen-salesforce-commerce-cloud/assets/49249098/ec700198-0a40-4ab3-93f7-9892821cf59e)

**Comment by amihajlovski** [comment]
Hello @georgi-il 

We will set an investigation regarding this and will keep you posted.

Kind Regards
Aleksandar
Adyen
