### ISSUE TITLE
Implement captureDelayHours in SFCC cartridge

### ISSUE THREAD

**Issue by nishad-ashraf** [Adyen/adyen-salesforce-commerce-cloud#1087]
**Is your feature request related to a problem? Please describe.**
We are using Adyen SFCC cartridges, and are having issues with Givex (via Adyen) not being able to process the payment capture because the capture request call is occurring immediately. Givex recommended **delaying the capture** to resolve this issue. The Adyen support team confirmed that, in the Adyen SFCC cartridge, the captureDelayHours is currently not sent in the payment request. They suggested if we customize the code, they will not be able to provide any support and further requested that we raise a feature request to send the **captureDelayHours** in the **payment request** itself, allowing the client to independently adjust the delay for each payment method.

**Describe the solution you'd like**
The payment request should include **captureDelayHours** so that the client can modify the capture delay for certain payments, such as Givex, without affecting other payments, such as credit card payments.

**Comment by zenit2001** [comment]
Hi @nishad-ashraf , 

I took a look on your request and discussed it with the support engineers. Ideally, this issue should be solved on a platform configuration rather than in a plugin configuration. 
To further investigate your issue, can you please log a case again to support@adyen.com, including this github issue as well as your previous ticket number. 

With kind regards,
Zenit 
Adyen

**Comment by nishad-ashraf** [comment]
Hi @zenit2001 ,
![image](https://github.com/Adyen/adyen-salesforce-commerce-cloud/assets/42961626/f3b8e627-1781-43cc-9756-5c2563112cbd)
I have already raised this with adyen support team and they guided to raise an enhancement request. Do you think I should go back again and raise another support ticket with the same details?

Thanks,
Nishad

**Comment by zenit2001** [comment]
Hi @nishad-ashraf , 

Yes, please do so. Also, include this issue in the ticket and someone from the support should be able to help.

With kind regards,
Zenit 
Adyen
