### ISSUE TITLE
Floating point math issue

### ISSUE THREAD

**Issue by khanhruby** [Adyen/adyen-salesforce-commerce-cloud#109]
We are having problems with floating point math.

```
File: int_adyen_overlay/cartridge/scripts/getPaymentMethodsSHA256.ds
Line: # 54

var paymentAmount: Number = basket.getTotalGrossPrice() ? AdyenHelper.getCurrencyValueForApi(basket.getTotalGrossPrice()) : 1000;
Ex: 288.15 * 100 = 28814.999999999996
```
There will be an error if requesting that value with Adyen's API.

I found the document on this issue here:
https://0.30000000000000004.com/
https://stackoverflow.com/questions/588004/is-floating-point-math-broken

**Comment by maassenbas** [comment]
Hi @khanhruby , 

I tried to reproduce this issue, but the return value for me is 28815 as expected.
Could you confirm this issue has been resolved? 

Thanks,
Bas Maassen
