### ISSUE TITLE
Domain Association Apple Pay

### ISSUE THREAD

**Issue by KennethRobbeFrucon** [Adyen/adyen-salesforce-commerce-cloud#1141]
**Describe the bug**
Logic was added inside [this PR](https://github.com/Adyen/adyen-salesforce-commerce-cloud/pull/1012/files) to always add a line break add the end of the domain association file for Apple Pay (`/.well-known/apple-developer-merchantid-domain-association`). This was added because the previous domain association file of Adyen included a line break at the end. However, the [new file](https://eu.adyen.link/.well-known/apple-developer-merchantid-domain-association) no longer contains this line break, so there's always a mismatch between the value that's presented by SFCC and the original value.

**To Reproduce**
1. Fill in the domain association value (without line break) through the preference-module
2. A line break is added at the end of the value on the SFCC URL (`/.well-known/apple-developer-merchantid-domain-association`)
3. It is not possible to activate the payment method on Adyen Production, as the values of the files don't match.

**Expected behavior**
Value presented by SFCC should no longer contain the line break.

**Comment by zenit2001** [comment]
Hi @KennethRobbeFrucon , 

Thanks for your report. Can you please provide us some more information: 

- In which version of the plugin you were able to reproduce this issue?
- By `preference-module` do you mean the Adyen Settings page on Business Manager? 

With kind regards,
Zenit
Adyen

**Comment by KennethRobbeFrucon** [comment]
Hi @zenit2001,

We're using  23.3.1, but the code that adds the line break is still present in the latest version:

https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/4da8a1d3392dd33e94a5581fc5db028ec1a249e6/cartridges/int_adyen_SFRA/cartridge/controllers/RedirectURL.js#L14

I've tried updating the value through both the Adyen settings page & the regular BM Site preferences module

Kind regards,
Kenneth

**Comment by zenit2001** [comment]
Hi @KennethRobbeFrucon , 

Thank you for your quick reply.
We will setup an investigation and keep you updated for the status.
In the meantime, in case you want to remove the line break, you can replace `println` with `print`.

With kind regards,
Zenit 
Adyen

**Comment by KennethRobbeFrucon** [comment]
Hi @zenit2001,

That's indeed what we have done at the moment. I can confirm that solves the issue.

Kind regards,
Kenneth

**Comment by zenit2001** [comment]
Hey @KennethRobbeFrucon , 

We have fixed the apple pay domain association issue on our latest [release](https://github.com/Adyen/adyen-salesforce-commerce-cloud/releases/tag/24.4.0).

Kind regards,
Zenit
Adyen
