### ISSUE TITLE
Problem wit Paypal express shipping methods AdyenPaypalUpdateOrder service

### ISSUE THREAD

**Issue by AVATOR** [Adyen/adyen-salesforce-commerce-cloud#1142]
**Describe the bug**
Service AdyenPaypalUpdateOrder sent request to add shipping methods to Paypal express window but I got error. Problem on EMEA sites. Currently I am testing on GB locale with GBP pricebook

**To Reproduce**
1. Go to Cart (EMEA locales)
2. Click on PayPal express
3. Wait for Paypal window load
4. open service log
5. See error

**Logs**
`INFO PipelineCallServlet|1557082651|Sites-***-emea-Site|Adyen-ShippingMethods|PipelineCall|IS56utOiOp custom.service.AdyenPaypalUpdateOrder.COMM []  
Request:
{
    "pspReference": "J9483VK****",
    "paymentData": "A*****",
    "amount": {
        "currency": "GBP",
        "value": 18195
    },
    "deliveryMethods": [
        {
            "reference": "DPD5",
            "description": "Standard Delivery",
            "type": "Shipping",
            "amount": {
                "currency": "GBP",
                "value": 395
            },
            "selected": true
        },
        {
            "reference": "DPD1",
            "description": "Next Day Delivery ",
            "type": "Shipping",
            "amount": {
                "currency": "GBP",
                "value": 595
            },
            "selected": false
        },
        {
            "reference": "DPD2",
            "description": "Saturday Delivery",
            "type": "Shipping",
            "amount": {
                "currency": "GBP",
                "value": 595
            },
            "selected": false
        },
        {
            "reference": "FEDMP1",
            "description": "Standard Delivery (2-4 weeks)",
            "type": "Shipping",
            "amount": {
                "currency": "GBP",
                "value": 0
            },
            "selected": false
        }
    ]
}`

`INFO PipelineCallServlet|1557082651|Sites-***-emea-Site|Adyen-ShippingMethods|PipelineCall|IS56utOiOp custom.service.AdyenPaypalUpdateOrder.COMM []  
Response:
{
    "status": 500,
    "errorCode": "903",
    "message": "Internal error",
    "errorType": "internal",
    "pspReference": "ZVD2S69BRRZPGS65"
}`

**Comment by zenit2001** [comment]
Hi @AVATOR ,

Thanks for reaching out to us.
Are you using the latest version of the plugin?
I tried reproducing the reported issue using the latest version of the plugin (v24.3.2), however I can't reproduce it. 

Can you please open a support ticket with Adyen, including the plugin version you used and details related to the failing transaction?
In case the issue comes from a plugin perspective, the support team will reach out to us and we will take care of the problem.

With kind regards,
Zenit 
Adyen

**Comment by AVATOR** [comment]
Hi @zenit2001 
I am using cartridge version 24.3.1

**Comment by zenit2001** [comment]
Hi @AVATOR ,

Please open a support ticket for the reported issue and they will help you solve the issue. It seems to be a configuration problem on the merchant account side, more than in plugin itself.
You can attach this thread there also for reference.

With kind regards,
Zenit
Adyen

**Comment by AVATOR** [comment]
Thanks @zenit2001 
Yes, it was a configuration issue.

**Comment by cayohenrique** [comment]
hey @AVATOR, what was the configuration issue? i'm facing the same problem
