### ISSUE TITLE
PayPal Express amount mismatch error for gross taxation

### ISSUE THREAD

**Issue by rradu-lbtech** [Adyen/adyen-salesforce-commerce-cloud#1155]
**Describe the bug**
In the Paypal Update Order call, for sites with a gross taxation policy, the shipping cost is provided as a gross amount, with the associated taxes included in the total tax amount. 

**To Reproduce**
1. Add products to cart
2. Make sure the shipping is not free
3. Access PayPal

**Suggested Fix**
Subtract shipping tax amount from total tax for gross taxation policy
<img width="1500" alt="Screenshot 2024-08-30 at 09 57 59" src="https://github.com/user-attachments/assets/d239f104-95ec-4f7f-9541-5f6f58d79715">

**Comment by rradu-lbtech** [comment]
The issue is more complex than initially thought. 
When attempting to ship to a non-default country or switching between countries in the PayPal modal, the PayPal order update call fails. In version 24.3.2, the /payments call was updated to send the amount as the adjusted merchandising net amount.
However, during the order update call, if the taxes differ from those in the initial payment call, the initial adjusted net amount combined with the new calculated taxes will not match the new gross total. This discrepancy occurs only when taxation is set to Gross rather than Net.
Release 24.3.2 resolved issues related to Net taxation but introduced new problems for Gross taxation.

**Comment by zenit2001** [comment]
Hey @rradu-lbtech , 

We have fixed the taxation issue on our latest [release](https://github.com/Adyen/adyen-salesforce-commerce-cloud/releases/tag/24.4.0).

Kind regards,
Zenit
Adyen
