### ISSUE TITLE
Cardholder name limit should be increased

### ISSUE THREAD

**Issue by jkol** [Adyen/adyen-salesforce-commerce-cloud#124]
https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/457286dc26ce82748ba342f1edd3bd495e818a91/cartridges/int_adyen_SFRA/cartridge/forms/default/creditCard.xml#L21

The field seems to be too short. The WSDL reference a maxlength of 50 and the API references a maxlength of 80.

**Comment by bahagiga** [comment]
Side note: it's not a mandatory field
