### ISSUE TITLE
Utilize lowercase for cartridge names

### ISSUE THREAD

**Issue by jkol** [Adyen/adyen-salesforce-commerce-cloud#126]
Typically SFCC B2C cartridge names are all in lowercase.

Renaming int_adyen_SFRA to int_adyen_sfra would keep in line with standard cartridge naming conventions.

**Comment by maassenbas** [comment]
Hi @jkol , 

Thanks for the suggestion. 
I will create an internal ticket for it. 

Kind regards,
Bas Maassen
