### ISSUE TITLE
Not working with SFRA v4.0.0

### ISSUE THREAD

**Issue by vrushali-desai** [Adyen/adyen-salesforce-commerce-cloud#155]
I am unable to get the latest version of the cartridge to work with SFRAv4.0.0. The PaymentMethod comes out null in CheckoutServices-SubmitPayment. There's an issue regarding this on the link_adyen repo https://github.com/SalesforceCommerceCloud/link_adyen/issues/13.
Is this a known issue and are there any chances of it getting resolved soon?

**Comment by ScottPowell14** [comment]
Hi @vrushali-desai,

You can use the code on the develop branch on Github that is compatible with SFRAv4.0.0. We have submitted this for review to SF- after the review is complete, the link_adyen repo will be updated and we will do a new release on this repo as well.

Best,
Scott
Adyen

**Comment by fishme** [comment]
Hope it will also work with the newest version. 4.1.1 :)
