### ISSUE TITLE
Not defined variable "endpoint"

### ISSUE THREAD

**Issue by aduponchel** [Adyen/adyen-salesforce-commerce-cloud#157]
# Environment

* Adyen Payment 18.3.0
* SiteGenesis v104.1.3

# Setup

We have installed vanilla SiteGenesis and Adyen cartridge by following the documentation available here :  https://docs.adyen.com/plugins/salesforce-commerce-cloud/

# Issue

After following [Adyen online documentation](https://docs.adyen.com/plugins/salesforce-commerce-cloud/), we face to an issue.

https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/77452a678f51dfb8b20a755d900f2f187cf65b46/cartridges/int_adyen_overlay/cartridge/scripts/adyenCancel.ds#L55

https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/77452a678f51dfb8b20a755d900f2f187cf65b46/cartridges/int_adyen_overlay/cartridge/scripts/adyenCancelOrRefund.ds#L55

https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/77452a678f51dfb8b20a755d900f2f187cf65b46/cartridges/int_adyen_overlay/cartridge/scripts/adyenCapture.ds#L55

endpoint is never defined and lead to an not defined variable error.

Remove these lines of code seems to resolve the issue.

**Comment by aduponchel** [comment]
I confirm by doing a SG integration this is a real issue.
adyenCancel , adyenCapture and adyenCancelAndRefound scripts does not work

**Comment by ScottPowell14** [comment]
Hi @aduponchel,

It is true that these scripts do not work and are still there as part of the legacy implementation. As most of our merchants typically make modification (https://docs.adyen.com/development-resources/payment-modifications/) requests from an external OMS, these scripts are not currently maintained. 

Best,
Scott
Adyen
