### ISSUE TITLE
Error: Wrapped object may not be null due to a missing form element

### ISSUE THREAD

**Issue by aduponchel** [Adyen/adyen-salesforce-commerce-cloud#159]
# Environment

* Adyen Payment 18.3.0
* SiteGenesis v104.1.3

# Setup

We have installed vanilla SiteGenesis and Adyen cartridge by following the documentation available here :  https://docs.adyen.com/plugins/salesforce-commerce-cloud/

# Issue

After following [Adyen online documentation](https://docs.adyen.com/plugins/salesforce-commerce-cloud/), we face to an issue.

The form field `billing.paymentMethods.creditCard.encrypteddata` is mentionned multiple time in code but never exist. It leads to an `Error: Wrapped object may not be null`.

Adds 
```javascript
<field formid="encrypteddata" type="string" mandatory="false" binding="encrypteddata"/>
```
 to `app_storefront_core\cartridge\forms\default\creditcard.xml` seems to resolve the issue.
But this step is missing from documentation

**Comment by ScottPowell14** [comment]
Hi @aduponchel,

The documentation has been updated to reflect the cartridge changes made during an update to Adyen's Checkout API. Unfortunately, this version has not been certified by Salesforce, so we have not performed a release. Please find this code on the develop branch of this repo. The new implementation of Adyen's CSE splits the encrypted card data into 4 separate fields as you can see here: https://docs.adyen.com/plugins/salesforce-commerce-cloud/customize-storefront-code/#formsdefaultcreditcard-xml.

Please use the develop branch for your integration so it is consistent with the docs.

Best,
Scott
Adyen

**Comment by aduponchel** [comment]
Hi @ScottPowell14 ,
Could we have an access to the documentation for the certified version please ?
Demandware platform zip contains only an markdown file with only a link to the online documentation.
