### ISSUE TITLE
ReferenceError: "shown3dSecureForm" is not defined

### ISSUE THREAD

**Issue by aduponchel** [Adyen/adyen-salesforce-commerce-cloud#160]
Hello,

We have installed the Adyen on the latest version of SiteGenesis (104.X)
Following the Adyen documentation we have to add code in `controllers/COPlaceOrder.js` as described here : https://docs.adyen.com/plugins/salesforce-commerce-cloud/customize-storefront-code/

It seems to be a mistake and be : `show3dSecureForm`

**Comment by ScottPowell14** [comment]
Hi @aduponchel,

Thanks for pointing this out - I've asked our docs team to update this. Please ensure it is indeed declared and used as show3dSecureForm.

Best,
Scott
Adyen
