### ISSUE TITLE
Not Defined Variable 'view' on handlePayment

### ISSUE THREAD

**Issue by aduponchel** [Adyen/adyen-salesforce-commerce-cloud#161]
# Environment

* Adyen Payment 18.3.0
* SiteGenesis v104.1.3

# Setup

We have installed vanilla SiteGenesis and Adyen cartridge by following the documentation available here :  https://docs.adyen.com/plugins/salesforce-commerce-cloud/

# Issue

After following [Adyen online documentation](https://docs.adyen.com/plugins/salesforce-commerce-cloud/customize-storefront-code/#controllerscoplaceorder-js) about handlePayments step 3, we face to an issue.

```javascript
if(show3dSecureForm) {

  return{view : view};

}
```

Is also called when payment method is not Adyen and it make it crash because `view` is never defined.

We think theses lines are not usefull and could be removed as we already process 3DSecure lines above.

**Comment by maassenbas** [comment]
Hi @aduponchel ,

This code will indeed render Adyen's 3D Secure form. 
As described in the documentation, these code changes will be required for Adyen's cartridge. 
If you are also using other cartridges next to it, make sure that this is implemented accordingly.

Kind regards,
Bas Maassen

**Comment by aduponchel** [comment]
How could it be required meanwhile show3dSecureForm seems to be never set to truly value ?
Morover how could it be required as I mention the line `return{view : view};` leads to a Not Defined Variable.
It just take 2 minutes for doing a search "view" in file "COPlaceOrder" to see at this point view is used but is never defined.

We have planned to use an Adyen certified cartridge.
After following the documentation for the vanilla SiteGenesis, it does not work.
It ruined our roadmap.

I've take time identifying errors on YOUR certified cartridge.
I will appreciate if you could give me real answer instead of just telling me this is "not functionnal by design".

Thanks
Regards
