### ISSUE TITLE
Directory Lookup leads to unhandled Invalid Request response

### ISSUE THREAD

**Issue by aduponchel** [Adyen/adyen-salesforce-commerce-cloud#162]
# Environment

* Adyen Payment 18.3.0
* SiteGenesis v104.1.3

# Setup

We have installed vanilla SiteGenesis and Adyen cartridge by following the documentation available here :  https://docs.adyen.com/plugins/salesforce-commerce-cloud/

# Issue

After following [Adyen online documentation](https://docs.adyen.com/plugins/salesforce-commerce-cloud/customize-storefront-code/#controllerscoplaceorder-js), we face to an issue.

When Directory Lookup is enabled, it leads to an `SyntaxError: Unexpected token: &lt; (int_adyen_overlay/cartridge/scripts/getPaymentMethodsSHA256.ds#128`

Directory Lookup seems to parse as JSON a XML response.
After investigation we got an Invalid Request response whereas we followed the documentation to integrate the cartridge

**Comment by maassenbas** [comment]
Hi @aduponchel ,

After you enabled Directory Lookup, you will indeed receive a JSON response with the available payment methods for that order. These payment methods will be rendered on your checkout page, so a shopper will be able to choose his desired payment method. 

Could you make sure that you [imported](https://docs.adyen.com/plugins/salesforce-commerce-cloud/install-the-cartridge-and-import-the-metadata/#step-3-import-the-metadata) the meta data and that the services are configured correctly?

Kind regards,
Bas Maassen
