### ISSUE TITLE
Adyen capture use authorization service url

### ISSUE THREAD

**Issue by aduponchel** [Adyen/adyen-salesforce-commerce-cloud#164]
# Environment

* Adyen Payment 18.3.0
* SiteGenesis v104.1.3

# Setup

We have installed vanilla SiteGenesis and Adyen cartridge by following the documentation available here :  https://docs.adyen.com/plugins/salesforce-commerce-cloud/

# Issue

When capturing with a previously authorized order using adyenCapture.ds and fix bug referenced [here](https://github.com/Adyen/adyen-salesforce-commerce-cloud/issues/157) by removing bad code part.

Service use authorise url https://pal-test.adyen.com/pal/servlet/Payment/authorise instead of https://pal-test.adyen.com/pal/servlet/Payment/capture

**Comment by ScottPowell14** [comment]
I would suggest changing to a JSON request as follows (example for adyenCancel, but can be used for adyenCapture):

At this point in the code:

https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/develop/cartridges/int_adyen_overlay/cartridge/scripts/adyenCancel.ds#L69

You need to change the formatting of the params, like this:

```
var params = {};

params["merchantAccount"] = merchantAccount;
params["originalReference"] = pspReference;
```

And then replace the headers here: https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/develop/cartridges/int_adyen_overlay/cartridge/scripts/adyenCancel.ds#L81 

With this:

```
service.addHeader('Content-type','application/json');
service.addHeader("charset", "UTF-8");
callResult = service.call(JSON.stringify(params));
```

And indeed you will need to add in the service here:
https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/77452a678f51dfb8b20a755d900f2f187cf65b46/cartridges/int_adyen_overlay/cartridge/scripts/util/AdyenHelper.ds#L13

If you are able to, please open a PR with your changes.

Thanks,
Scott
Adyen
