### ISSUE TITLE
Adyen capture is not implemented

### ISSUE THREAD

**Issue by aduponchel** [Adyen/adyen-salesforce-commerce-cloud#165]
# Environment

* Adyen Payment 18.3.0
* SiteGenesis v104.1.3

# Setup

We have installed vanilla SiteGenesis and Adyen cartridge by following the documentation available here :  https://docs.adyen.com/plugins/salesforce-commerce-cloud/

# Issues
When fixed issues https://github.com/Adyen/adyen-salesforce-commerce-cloud/issues/164, making a capture request lead to an Adyen internal server error.

![image](https://user-images.githubusercontent.com/42732979/59910943-340bf880-9413-11e9-9c90-ae7cbb811b7f.png)

**Comment by ScottPowell14** [comment]
Hi @aduponchel,

See response to: https://github.com/Adyen/adyen-salesforce-commerce-cloud/issues/164#issuecomment-506434372

Best,
Scott
Adyen
