### ISSUE TITLE
Service call to AdyenOriginKeys returns 403 forbiden

### ISSUE THREAD

**Issue by VladStanimirOSF** [Adyen/adyen-salesforce-commerce-cloud#172]
I am using the develop version for SFRA 4.0 compatibility per suggestion in https://github.com/Adyen/adyen-salesforce-commerce-cloud/issues/155

However on Billing Page no card fields appear do to a javascript error.
"Cannot convert undefined or null to object" in adyenCheckout.js:31
This appears to be caused by the fact that the AdyenOriginKeys is failing with error message of 
{
    "error": {
        "code": 403,
        "message": "Forbidden",
        "requested URI": "/checkout//v1/originKeys"
    }
}
The API key is set in the BM and i tried setting the service credentials to that of the web service user however nothing works.
Only this service returns error 403

**Comment by maassenbas** [comment]
Hi @VladStanimirOSF , 

Your web service user might not have the correct permissions. 
Could you share you web service username? Then I can check this and make sure you are allowed to retrieve the originKeys. 

Thanks,
Bas Maassen
Adyen
