### ISSUE TITLE
Uncaught ReferenceError: di is not defined

### ISSUE THREAD

**Issue by gmoulin** [Adyen/adyen-salesforce-commerce-cloud#179]
Adyen v.19
Site Genesis last version

Checkout billing page:

The "ratepay" script is triggering an error.

Script URL: https://d.ratepay.com/oj9GsQ/di.js

Error message:
Uncaught ReferenceError: di is not defined
    at di.js:28
    at di.js:30

Can the "ratepay" script be safely commented in the "hpp.isml" template please?

**Comment by ScottPowell14** [comment]
Hi @gmoulin,

Can you confirm that you are using RatePay and have specified the RatePay ID in the Adyen Custom Preferences section in Business Manager?

Otherwise, this script should not be included.

Best,
Scott
Adyen

**Comment by gmoulin** [comment]
Hello,

I am not using it and I did not configure the RatePay ID in the preferences. 
The script is using the default value from the preferences (oj9GsQ)

![pref](https://user-images.githubusercontent.com/688073/61353178-72a89d80-a86f-11e9-977c-65e5b9ed98cf.png)

Regards,
Guillaume

**Comment by baharedankoyuncu** [comment]
Hi,
What's the status of this?

**Comment by gmoulin** [comment]
I commented it (since not used) and it does not seem to have any impact whatsoever.

**Comment by maassenbas** [comment]
Hi @gmoulin , 

We are looking into this issue now. 
I will keep you updated on the progress. 

Thanks,
Bas

**Comment by maassenbas** [comment]
Hi @gmoulin , @baharedankoyuncu , 

We solved the issue in the following PR: 
https://github.com/Adyen/adyen-salesforce-commerce-cloud/pull/189 

Kind regards,
Bas Maassen
