### ISSUE TITLE
Apple Pay support

### ISSUE THREAD

**Issue by gmoulin** [Adyen/adyen-salesforce-commerce-cloud#184]
It seems the support for Apple Pay payments is missing from the cartridge.

I will try to find what to add/change and where so it can work but it would be great if that was somehow documented or even part of the cartridge.

**Comment by maassenbas** [comment]
Hi @gmoulin , 

Apple pay will work with the built in functionality of SFCC. 
You can find the configuration here: 
https://docs.adyen.com/plugins/salesforce-commerce-cloud/set-up-payment-methods#set-up-apple-pay-on-the-web 

Kind regards,
Bas Maassen 
Adyen

**Comment by yogeshgadiya** [comment]
Hello Maassenbas,

After checking all the code with the newer version of Adyen 20.1.3. I don't see applePay rendering on OOTB SFRA 5.3/5.1
It is not coming in the checkout page with other payment methods.
Is additional code or step required not mentioned in the above document?
Confirm how it works via Plugin_applepay or direct via Adyen cartridges.

Thanks
Yogesh

**Comment by nnico** [comment]
Hello,

I'm interested too about this. I need to enable Apple Pay. I did the configuration liked it said in the documentation but nothing happen in front. 

Thanks,
