### ISSUE TITLE
Missing images for FINNISH E-BANKING

### ISSUE THREAD

**Issue by erwinfoekema** [Adyen/adyen-salesforce-commerce-cloud#2]
There are missing images for the payment method FINNISH E-BANKING.
In the folder **demandware-master\cartridges\int_adyen\cartridge\static\default\images** there are 527 images. 

When I look at the magento plugin, there are 545 images in the folder **magento-develop\skin\frontend\base\default\images\adyen** 

The problem can probably be fixed by copying the images, and changing the image names from the magento plugin. 

Example: In magento the image for nordea is called ebanking_FI_nordea.png
The demandware cartridge requires the name NORDEA.png

**Comment by rikterbeek** [comment]
Hi @erwinfoekema,

We have just launched a new cartridge online and this issue is solved.

Regards,
Rik
Adyen
