### ISSUE TITLE
Source link for payment method images

### ISSUE THREAD

**Issue by abe-tewolde** [Adyen/adyen-salesforce-commerce-cloud#216]
It looks like the old HPP format for images is being used rather than Checkout-shopper format described here: https://docs.adyen.com/checkout/api-only/downloading-logos.

Not sure if the HPP format is being updated as Sofort and Klarna both return images that say simply Klarna, rather than displaying a unique image for each payment method.

https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/43817faccc08b90a50d3924a325768b448879b7a/cartridges/int_adyen_overlay/cartridge/scripts/util/AdyenHelper.ds#L87

**Comment by maassenbas** [comment]
Hi @abe-tewolde,

I created an internal issue for this and will pick this up shortly. 
We will keep you updated.

Thanks,
Bas Maassen
Adyen

**Comment by msilvagarcia** [comment]
Hey @abe-tewolde ,

This is now merged into develop via pull request #219 and will be published in a future release.

Cheers!
Marcos
Adyen
