### ISSUE TITLE
Card Owner Name Length Validation

### ISSUE THREAD

**Issue by Terryda** [Adyen/adyen-salesforce-commerce-cloud#234]
I am on version 19.1 so I am not sure if this is still an issue. The credit card form field "cardOwner" has a max-length of 22. The field is hidden on the checkout and the Adyen Card Owner field has no client-side validation for limiting the length to 22. Therefore when you click review order, the credit card form fails validation on the server but the error is never pushed to the customer. Also, Adyen calls a full validation of the billing form but the field is missing a range-error so this field error is never placed on the response. This took forever to find out why validation was failing for the billing form with some 100 fields.

**Comment by maassenbas** [comment]
Hi @Terryda , 
I just investigated the issue and see that this still persists. 
I created an internal ticket for this and will update you once this is fixed. 

Thanks,
Bas Maassen 
Adyen

**Comment by maassenbas** [comment]
Hi @Terryda , 

I merged the fix in the develop branch with this PR:
https://github.com/Adyen/adyen-salesforce-commerce-cloud/pull/236

Thanks for noticing. 

Kind regards,
Bas Maassen
Adyen
