### ISSUE TITLE
Is the cartridge path intended?

### ISSUE THREAD

**Issue by G4M3RZTWITCH** [Adyen/adyen-salesforce-commerce-cloud#251]
In the below image we see the overlay cartridge in the path after the SFRA cartridge.  Am I just getting the naming convention mixed up?  normally the intended pathing is "override cartridge:SFRA cartridge: Base cartridge".  Is this intended?

![image](https://user-images.githubusercontent.com/4407038/78057130-1624da00-733b-11ea-960b-35d741f024b9.png)

**Comment by maassenbas** [comment]
Hi @G4M3RZTWITCH , 

Yes, this is intended.
The "int_adyen_overlay" cartridge is mutual code for SFRA and SiteGenesis controllers. 
That's why we have to put "int_adyen_SFRA" first and then the "int_adyen_overlay" cartridge.

Kind regards,
Bas Maassen
Adyen

**Comment by G4M3RZTWITCH** [comment]
👍
