### ISSUE TITLE
Fatal errors appear when trying to save a card in 'My Account'

### ISSUE THREAD

**Issue by kuvitalii** [Adyen/adyen-salesforce-commerce-cloud#268]
**Description**
When a user saves cart in 'My Account', the ID of AdyenNotification starts with recurringPayment-account. On the 51st line they split by '-', after it orderId contains ['recurringPayment'].
https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/develop/src/cartridges/int_adyen_overlay/cartridge/scripts/handleCustomObject.ds#L51
Then on the 52nd line order is null.
https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/develop/src/cartridges/int_adyen_overlay/cartridge/scripts/handleCustomObject.ds#L52
On the 57th line orderId.indexOf('recurringPayment-') is always false because orderId contains ['recurringPayment'] without dash. It was cut on the 51st line.
https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/develop/src/cartridges/int_adyen_overlay/cartridge/scripts/handleCustomObject.ds#L57

**Steps to reproduce:**
1. Set up the cartridge for the production environment.
2. Go to 'My Account' and try to save a new card.
3. Set your email for fatal errors in Business Manager.

**Expected behavior**
The card is saved without errors

**Screenshots**
https://vitalii-ewave.tinytake.com/tt/NDMyNjM4OV8xMzYyODEyMg
https://vitalii-ewave.tinytake.com/tt/NDMyNjM5OV8xMzYyODEzNA

**Comment by maassenbas** [comment]
Hi @kuvitalii , 

Thanks for noticing this. 
I will update this in the cartridge and make sure this is included in the next release. 

Kind regards,
Bas Maassen
Adyen
