### ISSUE TITLE
Adyen alternative  payment failed for orders with many porducts and quantity 

### ISSUE THREAD

**Issue by StoyanYaytsarov** [Adyen/adyen-salesforce-commerce-cloud#289]
Hello

The error regarding this is : 

[2020-06-19 05:24:38.343 GMT] ERROR PipelineCallServlet|3286816|Sites-EU-Site|CheckoutServices-PlaceOrder|PipelineCall|k2fWU7R-v3 custom []  Error while executing script 'int_payflow_sfra/cartridge/controllers/CheckoutServices.js': Wrapped java.lang.IllegalArgumentException: Data size 10702  exceeds the limit of 10240 bytes. (int_adyen_overlay/cartridge/scripts/util/AdyenHelper.ds#177)at int_adyen_overlay/cartridge/scripts/util/AdyenHelper.ds:177at int_adyen_SFRA/cartridge/scripts/hooks/payment/processor/adyen.js:89 (Authorize)at int_adyen_SFRA/cartridge/scripts/checkout/adyenHelpers.js:45 (handlePayments)at int_adyen_SFRA/cartridge/controllers/CheckoutServices.js:171at modules/server/route.js:79 (next)at modules/server/middleware.js:42 (https)at modules/server/route.js:87

This is in the Adyen OOB code the cartridge (int_adyen_overlay/cartridge/scripts/util/AdyenHelper.ds#177). Here Adyen returns two parameters from service call and they are with relation with product quantity and numbers on product in cart. The bigger cart is (number of products and their quantity), the bigger these params are. (longer in term of String class). And if these parameters are big enough the error appears.

The code content is :

getAdyenHash: function(value, salt){
    var data = value + salt;
    var signature = new 
    dw.crypto.MessageDigest(dw.crypto.MessageDigest.DIGEST_SHA_512).digest(data);
    return signature;
},
Here on the row 4, Adyen uses some depricated method  digest(string)  which causes the problem.

Here is SFCC  documentation regarding this class:

https://documentation.b2c.commercecloud.salesforce.com/DOC3/topic/com.demandware.dochelp/DWAPI/scriptapi/html/api/class_dw_crypto_MessageDigest.html?resultof="MessageDigest" "messagedigest" 

 

Infact the conversion from String to Bytes failed because of big String. This String is also received through call to Adyen services. So in conclusion this is existing bug in Adyen code for payment with redirect (in our case all Adyen alternative payment methods)

**Comment by maassenbas** [comment]
Hi @StoyanYaytsarov , 
Thanks for reaching out. 

We created an update on the getAdyenHash method in following commit: 
https://github.com/Adyen/adyen-salesforce-commerce-cloud/commit/2023d6fc95269e1f504cc479ce0ea4228d9008c3

Could you verify if this will solve your issue? 

Thanks,
Bas Maassen
Adyen

**Comment by StoyanYaytsarov** [comment]
Hello @maassenbas 
The code seems to work but now while I am testing the service for test environment returns **result.RedirectObject.url** while before it was **result.redirectObject.url** One upper case ! . Which is correct ?

**Comment by StoyanYaytsarov** [comment]
![12332123](https://user-images.githubusercontent.com/28441227/85501198-8e730280-b5ed-11ea-8024-55f5ffb87b67.jpg)

**Comment by StoyanYaytsarov** [comment]
Maybe it's change in servie call that you did

**Comment by maassenbas** [comment]
Hi @StoyanYaytsarov , 
Thanks for confirming that the code is working now.
We updated everything to camel case for the upcoming release, so it will be "redirectObject" with a lowercase.
