### ISSUE TITLE
Invalid order ID in process job

### ISSUE THREAD

**Issue by IvannaPikhOSF** [Adyen/adyen-salesforce-commerce-cloud#305]
In customObject notifications processing job the order ID is obtained in wrong way. For example, if the order ID looks like **ORDER-42**, the `customObj.custom.orderId` will be similar to ORDER-42-123456, the referenced code will return just **ORDER**

https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/6622607f743a8b77b6ab70e07c2dc0d7f08c358f/src/cartridges/int_adyen_overlay/cartridge/scripts/handleCustomObject.js#L50-L51

**Comment by maassenbas** [comment]
Hi @IvannaPikhOSF , 

Could you update your OrderNo to "ORDER_42" instead for example? 

Kind regards,
Bas Maassen
Adyen

**Comment by IvannaPikhOSF** [comment]
@maassenbas In case there are no extra '-' symbols in orderId, the error doesn't reporoduce. I believe the requirement should be at least documented.

**Comment by maassenbas** [comment]
Thanks @IvannaPikhOSF , we will look into this.
