### ISSUE TITLE
Problems with saved card - Adyen for Platforms

### ISSUE THREAD

**Issue by alinesab** [Adyen/adyen-salesforce-commerce-cloud#375]
Hello, we changed the "account holder" transactions on the SFCC plugin, so... the transaction is not approved with a saved card, just with new cards.

The error is 
{"status":422,"errorCode":"800","message":"Contract not found","errorType":"validation","pspReference":"881601406845996E"}

the transaction was created on SFCC but don't generate PSP number

![Uploading image.png…]()

**Comment by zaiddreakh** [comment]
Hi @alinesab 
It seems that this is more of a technical issue rather than a bug in the code.
Can you please open a ticket [here](https://www.adyen.help/hc/en-us/requests/new?ticket_form_id=360000705420) and our tech support team will assist you right away.

Cheers,
Zaid
Adyen
