### ISSUE TITLE
Missing formal parameter error after update to 20.1.2

### ISSUE THREAD

**Issue by oksana-yudenko** [Adyen/adyen-salesforce-commerce-cloud#389]
After update of the cartridge to 20.1.2 version (our current stable branch is release-19.2.2) our sandbox failed on the the page with the list of payment methods with the error "missing formal parameter" pointing to the code line with the trailing comma after the last function argument here

`function getSelectedPaymentInstruments(selectedPaymentInstruments) {
  return collections.map(
    selectedPaymentInstruments,
    createSelectedPaymentInstruments,
  );
}`

After research it was found that our sandbox Rhino engine does not support this javascript syntax (I mean trailing commas in the function arguments).

Sandbox version: Version: 20.10 Last Updated: Oct 22, 2020 (Compatibility Mode: 19.10)

**Comment by maassenbas** [comment]
Hi @oksana-yudenko ,
 
You will have to transpile the code before uploading it to your sandbox as described in the [documentation](https://docs.adyen.com/plugins/salesforce-commerce-cloud/install-the-cartridge-and-import-the-metadata#step-3-build-the-code). 

Please read the documentation how to setup and configure version 20.x.x of the cartridge.

Kind regards,
Bas Maassen
Adyen

**Comment by oksana-yudenko** [comment]
Hello @maassenbas,
Thank you for help!
