### ISSUE TITLE
Google Pay does not work in LIVE mode

### ISSUE THREAD

**Issue by macfiss** [Adyen/adyen-salesforce-commerce-cloud#392]
**Describe the bug**
We found that in the code of your cartridge a bug. In Live mode, you do not pass the mandatory merchantId attribute.
<img width="500" alt="Screen Shot 2020-11-16 at 16 24 57" src="https://user-images.githubusercontent.com/10142745/99541851-62a05100-29c2-11eb-91d6-408228677665.png">

**To Reproduce**

1) According to the [Checkout.js : 26 line](https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/20.1.2/src/cartridges/int_adyen_SFRA/cartridge/controllers/Checkout.js#L26) value of "environment" property is changed to LowerCase and later in [adyenCheckout.js : 158 line](https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/20.1.2/src/cartridges/int_adyen_SFRA/cartridge/client/default/js/adyenCheckout.js#L158) it doesn't pass the condition as 'live' !== 'LIVE'

<img width="400" alt="Screen Shot 2020-11-16 at 16 23 02" src="https://user-images.githubusercontent.com/10142745/99542248-e65a3d80-29c2-11eb-91ee-2a58c24be786.png">
<img width="500" alt="Screen Shot 2020-11-16 at 16 21 54" src="https://user-images.githubusercontent.com/10142745/99542304-f40fc300-29c2-11eb-9808-1e52c3812e39.png">

2) The second issue is that in [adyenCheckout.js : 159 line](https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/20.1.2/src/cartridges/int_adyen_SFRA/cartridge/client/default/js/adyenCheckout.js#L159) (when we will pass condition described in 158) MerchantID should be set to 'checkoutConfiguration.paymentMethodsConfiguration.paywithgoogle.merchantIdentifier' when MerchantID should be set to 'checkoutConfiguration.paymentMethodsConfiguration.paywithgoogle.**configuration**.merchantIdentifier' because it is used by the <wo> function:

<img width="500" alt="Screen Shot 2020-11-16 at 16 28 06" src="https://user-images.githubusercontent.com/10142745/99542697-6bdded80-29c3-11eb-91ea-fc389331e6d8.png">

**Expected behavior**
The MerchantID must be passed to GooglePay and to issue the customer the correct invoice for payment.

**Desktop:**
 - OS: Mac OS
 - Browser: Chrome
 - Version: 86.0.4240.183

**Additional context**
After the fix, please test the code in production mode.

**Comment by maassenbas** [comment]
Hi @macfiss ,

Thanks for creating this issue. 
I think you are right on both points.
Let me create an internal ticket for this to test it and update it accordingly. 

I will keep you updated. 

Kind regards,
Bas Maassen 
Adyen

**Comment by zaiddreakh** [comment]
Hey @macfiss,

We created and merged a PR for this https://github.com/Adyen/adyen-salesforce-commerce-cloud/pull/396

Kind regards,
Zaid
Adyen
