### ISSUE TITLE
Transactions created twice

### ISSUE THREAD

**Issue by BilalDev** [Adyen/adyen-salesforce-commerce-cloud#401]
Hello,

Our merchant account experiences an issue with transactions that are created twice, one remaining as open offer and the second converts correctly into a received transaction.

We already contact the support team and they asked us to create a bug report.

Cheers,
Bilal

**Comment by maassenbas** [comment]
Hi @BilalDev ,

Thanks for reaching out.
Which version of the cartridge are you using? Did you do any customisations? 

Are you able to reproduce this issue? 
Can you verify that you execute OrderMgr.failOrder() for the first transaction? 
This should fail the initial order, reopen the basket and create a new order with new order no. 

Thanks,
Bas Maassen
Adyen

**Comment by YanP-Adyen** [comment]
Hey @maassenbas , this is related to ticket #1726972

**Comment by BilalDev** [comment]
Hello @maassenbas,

Thank you for you quick answer.

We are using a custom version of the cartridges version 19.2.2.

Unfortunately I cannot reproduce this issue. It seems that it happens randomly.

Cheers,
Bilal

**Comment by maassenbas** [comment]
Hi @BilalDev ,
Checking the logs, I see multiple requests coming in for the same order.
This will be processed accordingly and send back the result for both payments.

Could you verify whether your customised code handles the resultCode correctly after a payment request? 
See the default code here: 
https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/19.2.2/cartridges/int_adyen_SFRA/cartridge/controllers/Adyen.js#L274 

Also, if the initial payment was not successful, could you verify whether that order gets failed with OrderMgr.failOrder()? 
https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/19.2.2/cartridges/int_adyen_SFRA/cartridge/controllers/Adyen.js#L299 

This should reopen the basket and create a new orderNo. 
This way it would not be possible to initiate two payment requests with the same orderNo. 

Kind regards,
Bas Maassen
Adyen

**Comment by BilalDev** [comment]
@maassenbas no customisation has been done to this file.

The resultCode is handle correctly :
`if (result.resultCode == "Authorised" || result.resultCode == 'Pending' || result.resultCode == 'Received')`

And the failOrder is being called line 299 when payment was not successful.

Cheers,
Bilal

**Comment by BilalDev** [comment]
Hello @maassenbas,

It's still happening on our website as of today. Can we debug it together maybe?

Cheers,
Bilal

**Comment by BilalDev** [comment]
Hello @maassenbas, I was able to reproduce the issue on dev sandbox.

There is a double execution of this hook : https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/19.2.2/cartridges/int_adyen_SFRA/cartridge/scripts/checkout/adyenHelpers.js#L42

I am very confused as there is only one execution of the for loop (only one paymentInstruments).

Cheers,
Bilal

**Comment by BilalDev** [comment]
I think I found the problem. Our integrator added two hooks.json in our code base. One from your cartridge (int_adyen_SFRA) and another one from our custom cartridge (app_custom_lesgeorgettes) where he added another payment hook.

Do you recommend to delete hooks.json from your cartridge and add all the payment hooks on our custom cartridge?

Or let Adyen payment hooks in int_adyen_SFRA/hooks.json and add our custom payment hooks in app_custom_lesgeorgettes/hooks.json?

Cheers,
Bilal

**Comment by maassenbas** [comment]
Hi @BilalDev ,

Thanks for the investigation.
I would recommend to use the payments hooks from the Adyen cartridge rather than the custom one. 

Kind regards,
Bas Maassen
Adyen
