### ISSUE TITLE
When PayPal dialog is closed before the content is loaded payment page is blocked - order is created but not failed

### ISSUE THREAD

**Issue by rumchoto** [Adyen/adyen-salesforce-commerce-cloud#403]
**Describe the bug**
If you open the PayPal dialog from the button and then close it before the PayPal content is loaded you cannot proceed with checkout. Order is created but there is no event on close to fail it so you have to start over the whole checkout process.

**To Reproduce**
1. Add some product to cart
2. Go to checkout page
3. Fill needed data
4. Select PayPal payment method
5. Click PayPal button
6. Close the dialog before the PayPal login is loaded
7. Try to pay again

**Expected behavior**
On close of PayPal dialog is expected to be able to proceed the order either with the same payment method or different.
We expected the same behavior as on close of PayPal dialog when the PayPal content is loaded and onCancel function is called.

**Comment by zaiddreakh** [comment]
Hey @rumchoto,

Thanks for pointing this out. We created an internal ticket and will update you once it's been fixed.

Regards,
Zaid
Adyen

**Comment by rumchoto** [comment]
Hi @zaiddreakh,

Do you have any update on this issue?

Thanks,
Rumyana

**Comment by zaiddreakh** [comment]
Hi @rumchoto,

This issue was fixed with this PR
https://github.com/Adyen/adyen-salesforce-commerce-cloud/pull/411

Regards,
Zaid
Adyen

**Comment by rumchoto** [comment]
Hi @zaiddreakh,

Thank you for the update. 
We are looking forward to the next release.

Kind Regards,
Rumyana
