### ISSUE TITLE
SyntaxError: invalid object initializer (int_adyen_controllers/cartridge/controllers/Adyen.js#548)

### ISSUE THREAD

**Issue by milica-popovic-osf** [Adyen/adyen-salesforce-commerce-cloud#405]
**SyntaxError**
Sitegenesis 104.0.0 
Code version compatibility mode: 18.10
Adyen 20.1.3 

**To Reproduce**
Reach shipping page - 404 page will be presented instead 

ERROR PipelineCallServlet|19263707|Sites-SiteGenesis-Site|COShipping-Start|PipelineCall|UqVsEFTq6x custom []  Error while executing script 'app_storefront_controllers/cartridge/controllers/COShipping.js': SyntaxError: invalid object initializer (int_adyen_controllers/cartridge/controllers/Adyen.js#548)

    var jsonRequest = {
      paymentData: paymentInstrument.custom.adyenPaymentData,
      details: {
        MD,
        PaRes
      }
    };

It works with 

        details: {
          MD: MD,
          PaRes: PaRes
        }

Note: Code is transpiled

**Comment by zaiddreakh** [comment]
Closing because same issue as #406
