### ISSUE TITLE
SyntaxError error int_adyen_controllers/cartridge/controllers/Adyen.js#587

### ISSUE THREAD

**Issue by milica-popovic-osf** [Adyen/adyen-salesforce-commerce-cloud#406]
**SyntaxError**
Sitegenesis 104.0.0
Code version compatibility mode: 18.10
Adyen 20.1.3

**To Reproduce**
Reach shipping page - 404 page will be presented instead

ERROR PipelineCallServlet|16165454|Sites-SiteGenesis-Site|COShipping-Start|PipelineCall|UqVsEFTq6x custom []  Error while executing script 'app_storefront_controllers/cartridge/controllers/COShipping.js': syntax error (int_adyen_controllers/cartridge/controllers/Adyen.js#587)

function clearAdyenData(paymentInstrument) {
  Transaction.wrap(() => {
    paymentInstrument.custom.adyenPaymentData = null;
    paymentInstrument.custom.adyenMD = null;
  });
}

It works with
function clearAdyenData(paymentInstrument) {
  Transaction.wrap(function() {
    paymentInstrument.custom.adyenPaymentData = null;
    paymentInstrument.custom.adyenMD = null;
  });
}

Same for
cartridges/int_adyen_controllers/cartridge/scripts/payment/processor/Adyen_Component.js :116

Same for int_adyen_overlay/cartridge/scripts/adyenLevelTwoThreeData.js:61
ERROR PipelineCallServlet|28077616|Sites-SiteGenesis-Site|COSummary-Submit|PipelineCall|UqVsEFTq6x custom []  Error while executing script 'app_storefront_controllers/cartridge/controllers/COSummary.js': syntax error (int_adyen_overlay/cartridge/scripts/adyenLevelTwoThreeData.js#61)
	at int_adyen_overlay/cartridge/scripts/adyenCheckout.js:53

ERROR PipelineCallServlet|29120317|Sites-SiteGenesis-Site|COSummary-Submit|PipelineCall|UqVsEFTq6x custom []  Error while executing script 'app_storefront_controllers/cartridge/controllers/COSummary.js': invalid property id (int_adyen_overlay/cartridge/scripts/adyenLevelTwoThreeData.js#70)

ES6 is not supported, can you please update all occurrences or add a list in integration guide about compatible versions of Sitegenesis

**Comment by zaiddreakh** [comment]
Hey @milica-popovic-osf,

Thanks for pointing this out. It is indeed not transpiling properly on some environments.
in that case try replacing the contents of the file `babel.config.js` with
```
/* eslint-disable */
module.exports = function (api) {
  api.cache(true);
  return {
    presets: [["@babel/preset-env"]],
    plugins: [
      ["@babel/plugin-transform-runtime", { helpers: false }],
      "@babel/plugin-proposal-optional-chaining",
      ["@babel/plugin-proposal-decorators", { legacy: true }],
      "@babel/plugin-proposal-class-properties",
    ],
    exclude: "node_modules/**",
  };
};
```
and also install any missing modules (i.e. `@babel/plugin-proposal-decorators` and `@babel/plugin-transform-runtime`)

In the meantime we'll work on a proper fix for this for the following release.

Regards,
Zaid
Adyen

**Comment by zardoz773** [comment]
Hi, 
  I am using the last version of your cartdrige in SFRA and the trick worked.

I also had to make a correction in the transpiled Adyen.js at line 549.  I removed the JSON.parse of the variabile connectedTerminals.

Thank you
