### ISSUE TITLE
Attribute adyenMD missing in metadata

### ISSUE THREAD

**Issue by aquinzain** [Adyen/adyen-salesforce-commerce-cloud#412]
**Describe the bug**
Hi, it seems a new attribute adyenMD has been introduced in the last release code but is missing in the metadatas.
This custom attribute is used on paymentInstrument object, I see the attribute in develop branch but not on release 20.1.3.

**To Reproduce**
We were not able to reproduce the bug on development instance but only on production.
All card payments with 3DS finished with an error.

Here our logs from production :
Error while executing script 'int_adyen_SFRA/cartridge/controllers/CheckoutServices.js': ReferenceError: Unknown dynamic property 'adyenMD' for class 'class dw.object.ExtensibleObject$ExtensibleObjectAttributes'. (int_adyen_SFRA/cartridge/controllers/CheckoutServices.js#217) at int_adyen_SFRA/cartridge/controllers/CheckoutServices.js:217

We were able to solve this issue by adding the adyenMD attribute on OrderPaymentInstrument in metadata.

Regards,
Antoine

**Comment by zaiddreakh** [comment]
Hi @aquinzain,

Thank you for pointing this out.
The adyenMD attribute is indeed missing and adding it in the metadata like you did should solve the issue, so no further action is required from you.

For the record, Antoine's issue could be solved either directly from the business manager OR by adding the following attribute to the file `system-objecttype-extensions.xml` under an existing attribute (e.g. the attribute `adyenAction`)

```
  <attribute-definition attribute-id="adyenMD">
      <display-name xml:lang="x-default">adyenMD</display-name>
      <description xml:lang="x-default">Adyen MD for 3D Secure</description>
      <type>text</type>
      <mandatory-flag>false</mandatory-flag>
      <externally-managed-flag>false</externally-managed-flag>
      <min-length>0</min-length>
      <field-length>0</field-length>
  </attribute-definition>
  ```
And then re-importing the metadata as described [here](https://docs.adyen.com/plugins/salesforce-commerce-cloud/install-the-cartridge-and-import-the-metadata#step-4-import-the-metadata)

Let me know if you have other questions and apologies for the inconvenience.
Regards,
Zaid
