### ISSUE TITLE
Cannot read property "length" from undefined in int_adyen_overlay/cartridge/scripts/updateSavedCards.js:92

### ISSUE THREAD

**Issue by idorsebastian** [Adyen/adyen-salesforce-commerce-cloud#415]
**Describe the bug**
Billing page error when recurring payment is enabled and there are no stored payment methods

**To Reproduce**
1. Set "AdyenRecurringEnabled" custom preference to true
2. Create new customer account
3. Add products to the cart and go to the checkout billing step

The result is: updateSavedCards.js - function getOneClickPaymentMethods will throw a error: 
TypeError: Cannot read property "length" from undefined in int_adyen_overlay/cartridge/scripts/updateSavedCards.js:92

`var storedPaymentMethods = getPaymentMethods.getMethods(null, customer, '').storedPaymentMethods;` 
storedPaymentMethods will be undefined.
` for (var i = 0; i < storedPaymentMethods.length; i++) {` 

Best regards,
Sebastian

**Comment by maassenbas** [comment]
Hi @idorsebastian , 

Thank you for creating this issue. 
I will verify it on my end and create an internal ticket for it.
I will keep you updated.

Kind regards,
Bas Maassen
Adyen

**Comment by idorsebastian** [comment]
Hello @maassenbas, 

Thanks for your quick reply. I am using SiteGenesis version. 

Best regards,
Sebastian

**Comment by maassenbas** [comment]
Hi @idorsebastian ,

I was able to reproduce your issue. 
The issue is caused by the getPaymentMethods not having a proper response. 
Could you verify that your API key is configured correctly in the Custom Preferences? 
If so, could you check the customerror and service logs and see the response from the AdyenCheckoutPaymentMethods? 

Hope this will solve the issue. 
Please let me know if you have any further questions.

Kind regards,
Bas Maassen
Adyen

**Comment by idorsebastian** [comment]
Hi @maassenbas,

The Adyen response is not containing storedPaymentMethods at all if the customer did not save any card until that moment.

Thank you,
Sebastian

**Comment by maassenbas** [comment]
Hi @idorsebastian ,

To solve this issue, you can add an if statement before the loop starts, like this: 
```
  if(storedPaymentMethods) {
    for (let i = 0; i < storedPaymentMethods.length; i++) {
      if ( .........
```

I will make sure to include this also in the cartridge code.

Thanks,
Bas
