### ISSUE TITLE
Minor bug in BM : Payment method type is not displayed

### ISSUE THREAD

**Issue by milica-popovic-osf** [Adyen/adyen-salesforce-commerce-cloud#416]
**Minor bug**

ERROR PipelineCallServlet|556784439|Sites-Site|ViewOrder_52-Dispatch|PipelineCall|F6ttjQ-wsx custom.isml []  ReferenceError: Unknown dynamic property 'Adyen_PaymentMethod' for class 'class dw.object.ExtensibleObject$ExtensibleObjectAttributes' ([Template:order/PaymentInstrumentInfo_Adyen_Component:$
{order.custom.adyenPaymentMethod}
]#1)
	at [Template:order/PaymentInstrumentInfo_Adyen_Component:${order.custom.Adyen_PaymentMethod}]:1

**Solution** 
order.custom.adyenPaymentMethod
to be replaced with
order.custom.Adyen_paymentMethod 

**To Reproduce**
1. Open order in Business Manager, Payment type

**Additional context**
Sitegenesis 104.0.0
Code version compatibility mode: 18.10
Adyen 20.1.3

**Comment by maassenbas** [comment]
Thanks for opening the issue @milica-popovic-osf . 
We will have it fixed in the upcoming release.

Kind regards,
Bas Maassen
Adyen
