### ISSUE TITLE
Notification job only update payment status

### ISSUE THREAD

**Issue by aquinzain** [Adyen/adyen-salesforce-commerce-cloud#417]
**Describe the bug**
Hi, we have some orders on production which have been correctly paid in Adyen but they finally have been failed in SFCC.
In the Business Manager, we can see in the history that the order was in status created before the redirection to payment page (can be Oney, CB with 3DS), but the order was never placed.
After a few hours, based on the SFCC configuration, the order is automatically failed.

**To Reproduce**
1. Make a payment with external redirection, like Oney
2. When the payment is validated, close the page before redirection to the confirmation page
3. Check the order status after the notification process has been executed for your order

**Expected behavior**
We would expect a check on the order status in the notification process to prevent this kind of errors.
If the payment is confirmed but the order is still with status created, the order should be placed by the job.
Placing the order only on a front process is not 100% secure, some client can close the page, your phone can turn off etc...

**Comment by YanP-Adyen** [comment]
Merchant account : PacificPecheECOM
PSP examples : 1316120975492673 or 4516118227434404

**Comment by maassenbas** [comment]
Hi @aquinzain , 
Thanks for creating this issue.
I will investigate this and create an internal ticket for it. 

I will keep you updated.

Kind regards,
Bas Maassen
Adyen

**Comment by maassenbas** [comment]
Hi @aquinzain ,
We have fixed this issue with PR #426. 

Kind regards,
Bas Maassen
Adyen

**Comment by aquinzain** [comment]
Hi @maassenbas,

The fix has been approved on our side, but we had to fix two little things in adyenService.js on line 42 and 47

`    if (order.status === Order.ORDER_STATUS_CREATED) {

    if (order.status**.value** === Order.ORDER_STATUS_CREATED) {

      // custom fraudDetection

      const fraudDetectionStatus = { status: 'success' };

      const placeOrderResult = COHelpers.placeOrder(

        order,

        fraudDetectionStatus,

        fraudDetectionStatus

      );`

**Comment by maassenbas** [comment]
Thanks @aquinzain. 
Will close the issue now.

**Comment by soerensiegjensen** [comment]
Hi @maassenbas 

Found this issue and I think we might be having the same issue. I would like to implement this fix, but I have a question.
What are the reason for using a custom sendEmail function to generate the confirmation e-mail?
Why not use the COHelpers.sendConfirmationEmail() function? As you do in the Adyen.js Controller?
That would include any customization created for the order confirmation e-mail. 

Best regards
Søren
