### ISSUE TITLE
 Error message due to currency null

### ISSUE THREAD

**Issue by fabioGoncalves20** [Adyen/adyen-salesforce-commerce-cloud#418]
I got this message:

[2020-12-22 17:48:05.694 GMT] FATAL PipelineCallServlet| ....(removed data)... |akeQ_n_Lsb custom.Adyen [] Adyen: TypeError: Cannot call method "toString" of null in int_adyen_overlay/cartridge/scripts/util/adyenHelper.js:557

This is caused by this:

 ```
if (basket) {
      **paymentAmount = basket.getTotalGrossPrice() ? AdyenHelper.getCurrencyValueForApi(basket.getTotalGrossPrice()) : 1000;**
      currencyCode = basket.currencyCode;
    }
```

Sometimes you have basket but the basket.getTotalGrossPrice() (from Money Class) the money will exists, but will have N/A values and it generates error inside the getCurrencyValueForApi(Amount).

I think you check first if ' basket.getTotalGrossPrice().**isAvailable()** ' :
`**paymentAmount = basket.getTotalGrossPrice() && basket.getTotalGrossPrice().**isAvailable ?** AdyenHelper.getCurrencyValueForApi(basket.getTotalGrossPrice()) : 1000;**`

Many Thanks.

**Comment by zaiddreakh** [comment]
Hi @fabioGoncalves20,

Thank you for raising this issue. I will test it on my sandbox as well and will create an internal ticket to follow up on this.

Kind Regards,
Zaid
Adyen

**Comment by zaiddreakh** [comment]
The issue was addressed in this PR https://github.com/Adyen/adyen-salesforce-commerce-cloud/pull/442

Thanks,
Zaid
Adyen
