### ISSUE TITLE
Unable to add a new credit card from "My Account" when 3DS2 is enabled

### ISSUE THREAD

**Issue by ismailnguyen** [Adyen/adyen-salesforce-commerce-cloud#419]
**Describe the bug**
When 3DS2 is disabled from the Business Manager, customers are not able to add a new credit card from their account page.

**To Reproduce**
- Open the Business Manager
- Disable 3DS2 through Custom Preferencs (Merchant Tools > Custom Preferences > Adyen > Adyen3DS2Enabled)
- Open the storefront
- Login to your account
- Open the payment instrument list page
- No "Add a new card" button is displayed

**Expected behavior**
I should see an "Add a new card" button whatever 3DS2 is enabled or not.

**Screenshots**
![image](https://user-images.githubusercontent.com/11783843/107019109-9446de00-67a1-11eb-83ec-c7eed447dfb6.png)

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 88

**Smartphone (please complete the following information):**
 - Device: Desktop
 - OS: Windows

**Additional context**
Related PR which disable the "Add to card" button : https://github.com/Adyen/adyen-salesforce-commerce-cloud/pull/204
Issued line of code with this condition : https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/a7305effcfcad7ba0d464c275090451feb5b1357/src/cartridges/int_adyen_controllers/cartridge/templates/default/account/payment/paymentinstrumentlist.isml#L12

**Comment by zaiddreakh** [comment]
Hi @ismailnguyen,

Thank you for posting your question.
Saving a card through my account initiates a zero-auth transaction. Currently we don't support 3DS in our zero-auth flow yet I'm afraid, that's why we disable adding cards from "my account" when 3DS is enabled.

However, when 3DS is enabled, the shopper can still add the credit card through the normal checkout flow by selecting "save my card" on the card component.

Kind regards,
Zaid
Adyen

**Comment by ismailnguyen** [comment]
Hi @zaiddreakh,

Thank you for your answer.

What is blocking to implement this logic in My Account ?
As this is something which works on the Checkout, can't we use this logic into My Account page also ?

Is supporting 3DS in the zero-auth transaction something easily feasable ? If yes, we can take care of it on our custom cartridge overriding the zero-auth method.

Kind regards,
Ismaïl

**Comment by zaiddreakh** [comment]
We do have it in our backlog, we just haven't got to it yet as we haven't had many requests for it.

You can possibly implement it yourself based on this https://docs.adyen.com/online-payments/3d-secure/native-3ds2/web-component

Kind regards,
Zaid
Adyen
