### ISSUE TITLE
Error with promotion type order / Oney

### ISSUE THREAD

**Issue by aquinzain** [Adyen/adyen-salesforce-commerce-cloud#424]
**Describe the bug**
Hi, when we create a promotion  with promotion class "Order", we have an error with the Oney payment.

`TypeError: Cannot call method "divide" of null in int_adyen_overlay/cartridge/scripts/adyenGetOpenInvoiceData.js:68`

**To Reproduce**
1. Create a promotion with "Order" class
2. Add a product to the cart with this promotion applied
3. Select Oney payment method and validate the form
4. See error in logs

**Comment by maassenbas** [comment]
Hi @aquinzain ,

I was able to reproduce the issue and created a fix for it in this [PR](https://github.com/Adyen/adyen-salesforce-commerce-cloud/pull/443/files). 
It will be included in the next release.

Thanks,
Bas Maassen
Adyen
