### ISSUE TITLE
Unused services

### ISSUE THREAD

**Issue by ismailnguyen** [Adyen/adyen-salesforce-commerce-cloud#427]
**Describe the bug**
There are unused services on AdyenHelper.

[AdyenHelper](https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/develop/src/cartridges/int_adyen_overlay/cartridge/scripts/util/adyenHelper.js) have a `SERVICE` constant which contains `PAYMENT_3DSECURE` and `PAYMENTMETHODS` values but these two services don't exist on services definition XML file (https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/develop/metadata/site_import/services.xml).

**Expected behavior**
We should have only used and existing services on services constants.

**Comment by maassenbas** [comment]
Hi @ismailnguyen ,
Thanks for pointing this out.
Will remove it from the AdyenHelper and make sure it is included in the next release.

Kind regards,
Bas Maassen
Adyen
