### ISSUE TITLE
Critical - Handle notifiy null exception

### ISSUE THREAD

**Issue by ismailnguyen** [Adyen/adyen-salesforce-commerce-cloud#430]
**Describe the bug**
Impossible to read notifications from Adyen. There is an exception due to try to access to `null`.

**Error from log**
> Error while executing script 'int_adyen_controllers/cartridge/controllers/Adyen.js': TypeError: Cannot read property "stringValue" from undefined (int_adyen_overlay/cartridge/scripts/handleNotify.js#36) at int_adyen_overlay/cartridge/scripts/handleNotify.js:36 (notifyHttpParameterMap) at int_adyen_controllers/cartridge/controllers/Adyen.js:63 (notify) at app_occitane_controllers/cartridge/scripts/guard.js:155

**To Reproduce**
1. Go to Adyen Backoffice > Account > Server communication
2. Choose or add your website's Notification endpoint (mysandbox.demandware.net/..../en_US/Adyen-Notify)
3. Trigger a test notification

**Expected behavior**
The notification coming from Adyen should be handled by Adyen controller.

**Additional context**
The error happens on `int_adyen_overlay/cartridge/scripts/handleNotify.js` at line 31 (https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/develop/src/cartridges/int_adyen_overlay/cartridge/scripts/handleNotify.js#L31)

The code is trying to loop through `hpm.parameterNames` which is an array, but the iterator of the loop `param` is the index of the array `hpm.parameterNames`, so when the code tries to access to `hpm[param]` it won't work because `hpm` variable isn't an array but a Map, and we can't access to a map's element with an index like we can do with an array.

**Comment by maassenbas** [comment]
Hi @ismailnguyen ,
Could you please make sure that you have configured the Server Communication as stated in the [docs](
https://docs.adyen.com/plugins/salesforce-commerce-cloud/set-up-the-cartridge#set-up-notifications-in-the-adyen-customer-area)?
If so, what is your merchant account name? This way I would be able to check what is going wrong.

Thanks,
Bas Maassen
Adyen

**Comment by maassenbas** [comment]
Hi @ismailnguyen ,

Thanks for the suggestion.
I tested it all on my environment and see that it will have the outcome with the suggested loop, so no need to update it on the `handleNotify`.
I will close this issue for now.

Thanks,
Bas
