### ISSUE TITLE
Notifications for partial payments not handled in correct order

### ISSUE THREAD

**Issue by taurgis** [Adyen/adyen-salesforce-commerce-cloud#439]
**Describe the bug**
When working with Gift Cards that do not cover the full amount of the order, a secondary payment happens on the HPP of Adyen. For these types of payments 4 notifications are sent:

1. ORDER_OPENED
2. AUTHORISATION 1
3. AUTHORISATION 2
4. ORDER_CLOSED

Since the notifications are not sorted on processing, the ORDER_CLOSED event is not always handled as the last processed notification, and in some cases, the ORDER_OPENED is processed last. This causes the order to be stuck on "PARTIALLY PAID" rather than "Paid.

**To Reproduce**
Use a Generic Giftcard method that needs to be combined with a secondary payment method. 
E.g., payment needs to happen for 25$. 20$ is paid with a gift card, and 5$ is paid with a MasterCard.

Wait for the notifications to come in and see that notifications are processed in random order.

**Expected behavior**
The job must handle the ORDER_CLOSED notification as to the last always as the last of the bunch. The sorting needs to happen on the event data rather than the creation date of the custom object.

**Comment by maassenbas** [comment]
Fixed with #440
