### ISSUE TITLE
ORDER_CLOSED event does not check for success

### ISSUE THREAD

**Issue by taurgis** [Adyen/adyen-salesforce-commerce-cloud#440]
**Describe the bug**
The ORDER_CLOSED event does not check for success and puts the order on paid, even if the payment is not made completely.

**To Reproduce**
Pay with a partial payment system to receive an ORDER_CLOSED event like Giftcards.

**Expected behavior**
Partial payments that are not finished yet should not be processed as paid.

**Screenshots**
![image](https://user-images.githubusercontent.com/2530193/114675229-4e117c00-9d08-11eb-8aa7-e7db37090b5d.png)

![image](https://user-images.githubusercontent.com/2530193/114675008-1571a280-9d08-11eb-9c54-d1f62fe68730.png)

**Comment by maassenbas** [comment]
Hi @taurgis ,
Thanks for opening the issues regarding the notification handler. 
We created a fix for it in following [PR](https://github.com/Adyen/adyen-salesforce-commerce-cloud/pull/445/files).
This should also fix your created issues #439 and #441 . 

Kind regards,
Bas Maassen
Adyen
