### ISSUE TITLE
AUTHORISATION call does not check amount paid

### ISSUE THREAD

**Issue by taurgis** [Adyen/adyen-salesforce-commerce-cloud#441]
**Describe the bug**
The AUTHORISATION check in the notifications job does not check if the amount paid is enough to cover the full order. When working with Gift Cards and partial payments, there is a scenario where the order gets put on paid whilst it is actually only partially paid.

**To Reproduce**
1. Pay with gift card with HPP fallback
2. Customer pays part of the order with Gift card
3. Customer closes the browser
4. Notification arrives for ORDER_OPENED --> Set to partially paid
5. Notification arrives for AUTHORIZATION --> Order is set to paid and ready for export

**Expected behavior**
The order should remain partially paid if the authorization amount is too low to cover the order.

**Comment by maassenbas** [comment]
Fixed with #440
