### ISSUE TITLE
Cannot place the order with product options

### ISSUE THREAD

**Issue by BerkanCetinkayaOSF** [Adyen/adyen-salesforce-commerce-cloud#461]
**Describe the bug**

place an order with a product that has product options

Actual: 
error processing payment. Error message: Cannot read property "ID" from null more details: TypeError: Cannot read property "ID" from null in int_adyen_overlay/cartridge/scripts/util/lineItemHelper.js:32

Expected: Order should be placed

**Comment by BerkanCetinkayaOSF** [comment]
Hello @wboereboom ,

It's happening with all product options on our side. Example product

sanyo-dp19648M

![Screen Shot 2021-05-31 at 01 02 15](https://user-images.githubusercontent.com/49192724/120121405-e9bd5580-c1ab-11eb-906a-adf5ccd93e84.png)
Issue comes from here, productline item doesn't have product which causes the issue.
![Screen Shot 2021-05-31 at 01 01 30](https://user-images.githubusercontent.com/49192724/120121371-bed30180-c1ab-11eb-9223-e404c433af49.png)

Our compatibility mode is 21.2

**Comment by wboereboom** [comment]
We've looked into it, and the documentation clearly states that `lineItem.product` might be undefined in some cases.
Could you please verify that changing `return linteItem.product.ID` to `return lineItem.productName` resolves this issue for you? 

Wouter
Adyen

**Comment by BerkanCetinkayaOSF** [comment]
> return linteItem.product.ID

This is our fix:
![Screen Shot 2021-05-31 at 13 29 27](https://user-images.githubusercontent.com/49192724/120180314-46545b00-c214-11eb-93e8-144b2d8eb108.png)

**Comment by wboereboom** [comment]
@BerkanCetinkayaOSF Thanks again for your contribution!
The changes will be added to the next release of our Cartridge!

Regards
Wouter
Adyen
