### ISSUE TITLE
Cannot place order with bundle

### ISSUE THREAD

**Issue by BerkanCetinkayaOSF** [Adyen/adyen-salesforce-commerce-cloud#469]
**Describe the bug**
Add a bundle product to basket

Example product: sony-ps3-bundleM

Try to place an order.

Expected: Order should be placed.

Actual: Order cannot be placed and we have the following error on the BM Logs:

ERROR PipelineCallServlet|1126605955|Sites-Clos19_FR-Site|CheckoutServices-PlaceOrder|PipelineCall|MeBzaZw0Ci custom.Adyen []  error processing payment. Error message: Cannot call method "toString" of null more details: TypeError: Cannot call method "toString" of null in int_adyen_overlay/cartridge/scripts/util/adyenHelper.js:554

![Screen Shot 2021-06-03 at 11 20 05](https://user-images.githubusercontent.com/49192724/120612266-b3a6fc80-c45d-11eb-8654-79663c01af1f.png)

**Comment by wboereboom** [comment]
Hi @BerkanCetinkayaOSF,

Thank you for raising this issue.
We are aware of this problem (see #421) and have resolved it.
This issue should be resolved in the upcoming release of our plugin

Regards,
Wouter
Adyen

**Comment by BerkanCetinkayaOSF** [comment]
@wboereboom ,
you could at least share where you fix it exactly?

I see this:
https://github.com/Adyen/adyen-salesforce-commerce-cloud/pull/443

but it seems it fixes more than one issue...

This section would be enough for our fix?
![Screen Shot 2021-06-04 at 15 34 38](https://user-images.githubusercontent.com/49192724/120801852-63599880-c54a-11eb-9023-671fd5f44d67.png)

**Comment by wboereboom** [comment]
The PR you mentioned is indeed the one that fixed this issue.
Unfortunately we did not link it to issue #421 at that time.
The changes to lineItemHelper.js Should resolve the bundle issues

Regards,
Wouter
Adyen
