### ISSUE TITLE
adyenAction hitting quota limitation

### ISSUE THREAD

**Issue by suaterken** [Adyen/adyen-salesforce-commerce-cloud#470]
Hello,

While placing an order using a Credit Card with a 3D Secure test card 

Visa | 4917 6100 0000 0000 | 03/2030 | 737

Adyen cartridge is trying to store payload into paymentInstrument but it is hitting system quota, referring;
`if (handlePaymentResult.threeDS2) {
    Transaction.wrap(function () {
      paymentInstrument.custom.adyenAction = handlePaymentResult.action;
    });`

And the issue;
![image](https://user-images.githubusercontent.com/7967939/121530480-c3928380-c9fd-11eb-844a-8fe48466a47a.png)

Is there a fix or workaround already for that?

**Comment by maassenbas** [comment]
Hi @suaterken ,

Thanks for reaching out.
Which version of the cartridge are you using? 
Can you make sure that the `adyenAction` attribute's type is set to `text`? 
https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/develop/metadata/site_import/meta/system-objecttype-extensions.xml#L99 

Please note that this value used to be `string` in older versions of the cartridge.

Hope this helps.

Kind regards,
Bas Maassen
Adyen

**Comment by suaterken** [comment]
Hello @maassenbas,
We have been using an old version (19.1.0) to a new one 20.1.0.
But indeed, after changing the type from string to text, it seems to be working after all.
Thank you for the quick response.
