### ISSUE TITLE
Unable to use Klarna Payment with discount code applied

### ISSUE THREAD

**Issue by soerensiegjensen** [Adyen/adyen-salesforce-commerce-cloud#471]
**Describe the bug**
Our customers is unable to use Klarna Invoice Payments if a coupon code is applied.
With the coupon code applied the customers is not redirected to Klarna in the storefront and an error messages is logged in Log Center.
The error message logged is:
error processing payment. Error message: Cannot call method "divide" of null more details: TypeError: Cannot call method "divide" of null in int_adyen_overlay/cartridge/scripts/adyenGetOpenInvoiceData.js:68
**To Reproduce**
1. Apply a coupon with promotion class order
2. Select a Klarna Payment option
3. Payment is failing at the confirm order step
4. The error above is logged in the Log Center

**Comment by wboereboom** [comment]
Hi @soerensiegjensen,

Thanks for raising this issue.
This issue was addressed before in #424 , and will be fixed in the upcoming release of the cartridge.
Our release is under review by SalesForce right now and will be released when they approve it.

Regards,
Wouter
Adyen

**Comment by soerensiegjensen** [comment]
Hi @wboereboom 

Sorry for missing the duplicate of the issue.
Do you have an expected timeframe for when the new version will be released?

Best regards
Søren

**Comment by wboereboom** [comment]
No worries @soerensiegjensen,

I'd rather risk a duplicate issue than miss a major bug 😉 .
We're dependent on SalesForce to review the cartridge, so unfortunately it is out of our control at this point.
As soon as they approve we can make our release without any delay on our end.

As an intermediate solution you can copy the changes made in the PR I referred to in my previous message.

Regards,
Wouter
Adyen

**Comment by soerensiegjensen** [comment]
Hi @wboereboom 

Looks like the new release of the cartridge is a bigger upgrade. Would like to wait until after the holiday season.
But I really want this fix for Klarna implemented. Looks like the PR you linked to includes multiple updates.
Which of the changes should I implement to fix the Klarna issue?

Best regards
Søren

**Comment by wboereboom** [comment]
Hi @soerensiegjensen,

I'm not sure which version of the cartridge you are on exactly, but I understand the upgrade is a hard one to do, especially with the holiday season around the corner.

The errors you are getting are related to the LineItemHelper class as far as I am able to tell.
the changes in `src/cartridges/int_adyen_overlay/cartridge/scripts/util/lineItemHelper.js` in the PR I linked should help you out.

This change always ensure a value is returned as opposed to `null` when retrieving Item and VAT amounts, which in turn caused the errors when calling the `divide` function in the `adyenGetOpenInvoiceData ` class.

Don't hesitate to reach out when things remain unclear.

Regards,
Wouter,
Adyen

**Comment by soerensiegjensen** [comment]
Hi @wboereboom 

Thank you very much for quick and useful help. It is very much appreciated. 

We are currently running on v20.1.3. I have seen the release notes for the two new releases, but do you have some documentation or guidelines regarding upgrading to the new version? Anything I need to be aware of when doing the upgrade?

For now I have updated lineItemHelper.js with the 3 changes from the PR you linked. It looks like it is working. I am able to continue to the Klarna redirect page now and I can see the discount is applied on the Klarna summary as well.

Thank you very much for the help.

Best regards
Søren

**Comment by wboereboom** [comment]
Hi @soerensiegjensen,

We are currently working to upgrade our docs with more information on how to upgrade.
But basically:
- make sure to reimport the metadata so all system objects and services get updated
- try to find out what customizations you made, so you can predict which of them might break. On top of that; always try to make customizations in a separate cartridge so you can turn them on/off, and to make sure you can easily update them too once you update the Adyen cartridge.

Regards,
Wouter
Adyen
