### ISSUE TITLE
Issue with saved card on SFCC OMS with Adyen Payment Package

### ISSUE THREAD

**Issue by BerkanCetinkayaOSF** [Adyen/adyen-salesforce-commerce-cloud#476]
Hello,

When placing an order with a saved card, the Order doesn't work properly on the OMS side.
We're using following package on OMS Side.
https://appexchange.salesforce.com/appxListingDetail?listingId=a0N3u00000ON7RtEAL

We believe the issue comes from this section (adyenPaymentMethod):
![Screen Shot 2021-06-25 at 11 58 35](https://user-images.githubusercontent.com/49192724/123398874-ad172b00-d5ac-11eb-890f-e8d3b104da28.png)
Not OK
![image (4)](https://user-images.githubusercontent.com/49192724/123399488-53fbc700-d5ad-11eb-92d3-4496d83eed0a.png)

This works perfectly fine on OMS side.
![Screen Shot 2021-06-25 at 11 59 18](https://user-images.githubusercontent.com/49192724/123398987-c91acc80-d5ac-11eb-8459-9c69fa22fd5f.png)
![image (5)](https://user-images.githubusercontent.com/49192724/123399705-99b88f80-d5ad-11eb-8104-e148082233e7.png)

So the question is: Any reason to have credit card number instead of payment method?

And How can we fix this issue?

Thanks

**Comment by maassenbas** [comment]
Hi @BerkanCetinkayaOSF ,

Thanks for reaching out. 
Which version of the cartridge are you using? 
How are you synchronising the orders from SFCC to OMS (e.g. import/export or API)? Could you verify whether the `cardType` is available for saved cards as well as new credit cards in your order's paymentInstrument? 

Best regards,
Bas Maassen
Adyen

**Comment by BerkanCetinkayaOSF** [comment]
> Which version of the cartridge are you using?
Hello @maassenbas , 

 - SFCC the latest one master (20.1.3)
 - OMS version Winter '21 1.4 (if OMS)

> How are you synchronising the orders from SFCC to OMS (e.g. import/export or API)? 
- B2C Integration OOTB (which is API)

> Could you verify whether the `cardType` is available for saved cards as well as new credit cards in your order's paymentInstrument?

Yes on OMS side

**Comment by maassenbas** [comment]
Hi @BerkanCetinkayaOSF ,

After some investigation on our end, I found out that we are not setting the `cardType` properly for saved cards. This will probably be the issue that it is not recognised in the OMS. 

I created an internal ticket for this and will try to pick it up next sprint. 
Will update you once it is implemented. 

Thanks for pointing this out.

Best Regards,
Bas Maassen
Adyen

**Comment by BerkanCetinkayaOSF** [comment]
> Hi @BerkanCetinkayaOSF ,
> 
> After some investigation on our end, I found out that we are not setting the `cardType` properly for saved cards. This will probably be the issue that it is not recognised in the OMS.
> 
> I created an internal ticket for this and will try to pick it up next sprint.
> Will update you once it is implemented.
> 
> Thanks for pointing this out.
> 
> Best Regards,
> Bas Maassen
> Adyen

Thanks @maassenbas, 

More info for next sprint, when release will be done?

Is there any workaround we can use for now?

Thanks

**Comment by BerkanCetinkayaOSF** [comment]
@wboereboom,  any update? I'm waiting your answer here

**Comment by wboereboom** [comment]
Hi @BerkanCetinkayaOSF ,

We're currently working on the solution for this issue.
Sorry to make you wait!
I'll make sure to link the PR to this issue as soon as we solve it.

Regards,
Wouter
Adyen

**Comment by wboereboom** [comment]
Hi @BerkanCetinkayaOSF ,

We have fixed the issue and merged it to develop.
Unfortunately we are still waiting on approvals before we can start making official cartridge releases again. 
For now you can view the PR referenced in this issue to see the changes.

Thanks again for pointing this issue out to us!

Kind regards,
Wouter
Adyen

**Comment by BerkanCetinkayaOSF** [comment]
Hi @wboereboom , thanks for the information :)
