### ISSUE TITLE
Add PayPal Express Options

### ISSUE THREAD

**Issue by ghost** [Adyen/adyen-salesforce-commerce-cloud#479]
Add express options 
- Paypal
- Amazon Pay

**Comment by ta-benhon** [comment]
Hey there,

Could Apple Pay be added to this list as well?

Thanks in advance,

**Comment by codyluth** [comment]
Hello,

Curious if there is a timeline on this? Our company really wants express options available to customers.

Thanks

**Comment by wboereboom** [comment]
hi @ta-benhon, @codyluth,

Apple Pay is supported through the cartridge provided by SFCC itself and already supports express Checkout. instructions on how to set that up can be found on our [docs](https://docs.adyen.com/plugins/salesforce-commerce-cloud/set-up-payment-methods#set-up-apple-pay-on-the-web)
As of yet we do not have a timeline for express options for Amazon Pay and Paypal.

Kind regards,
Wouter
Adyen

**Comment by bhunter** [comment]
Hi,
For PayPal express checkout, is the design challenge solely on the cartridge code or does the Adyen platform need work as well?
To put it another way could someone using this cartridge write a PayPal express implementation with the latest existing Adyen components and API version?

Thanks in advance!

**Comment by codyluth** [comment]
Hello!

It seems that it would be possible if we used the PayPal component in Adyen. We had PayPal Express on our previous payment provider and the buttons this component provides seems to match that.

https://docs.adyen.com/payment-methods/paypal/web-component#layout

Currently we seem to be limited to the PayPal checkbox option on the drop-in component in checkout. We're hoping to expand PayPal options (and Apple Pay) to our cart pages and possibly our Product Display Pages.

Thanks,
Cody
________________________________

**Comment by vmklaassens** [comment]
Hi @bhunter @codyluth,

Happy 2022!

Thanks for your contribution and feedback.

We as Adyen, are currently building a scalable and solid solution around express payment methods, as this is a noticeable trend which most likely will impact more payment methods. Therefore this is not available yet. In terms of expectations around our SFCC cartridge we expect to have this available in Q4 2022. 

In terms of ApplePay, it is currently possible to use the express payment option on ApplePay by using it via the Salesforce integration, which we explained in our docs [here](https://docs.adyen.com/plugins/salesforce-commerce-cloud/set-up-payment-methods#set-up-apple-pay-on-the-web). 

Best,
Vivienne

**Comment by codyluth** [comment]
That's great news. Thank you for the update and we look forward to that release!

**Comment by codyluth** [comment]
Hi @vmklaassens !

Is this feature still on track for a Q4 2022 release? We are planning internally to determine when we can start our update for this cartridge.

Thanks,
Cody

**Comment by codyluth** [comment]
Hi @vmklaassens,

I am excited to see that this has recently been moved into "Now".

Previously I had only mentioned PayPal Express as an additional express option we would like.  As it happens my company would now like to add Google Pay and Amazon Pay to that list of express options.

We'll take what we can, just curious if this ticket would move forward strictly as PayPal only, or would it capture other methods as well?

Thanks,
Cody

**Comment by vmklaassens** [comment]
Hi @codyluth,

Thanks for reaching out and apologies for the delay, I somehow missed your message.

ATM we are working on ApplePay Express (totally via Adyen), AmazonPay express and Paypal express. We expect to launch **ApplePay exp** and **AmazonPay exp** in the very near future followed by PayPal exp.

Google Pay express as of now is not on our roadmap, happy to chat more about the reach/volume your company is expecting with it.

Best is to watch our repo and you will get an update on when the new release is out.

Cheers,
Vivienne

**Comment by zenit2001** [comment]
Hi everyone, 

Our [latest release](https://github.com/Adyen/adyen-salesforce-commerce-cloud/releases/tag/24.3.0) contains the implementation of PayPal Express on cart and mini-cart page.
Currently our cartridge supports Apple Pay Express, Amazon Pay Express and PayPal Express.

Kind regards,
Zenit
Adyen
