### ISSUE TITLE
AdyenOriginKeysLive is not listed in https://ca-live.adyen.com/ca/ca/config/accountapi.shtml

### ISSUE THREAD

**Issue by BerkanCetinkayaOSF** [Adyen/adyen-salesforce-commerce-cloud#501]
Hello,

Wonder why it's not listed AdyenOriginKeysLive at https://ca-live.adyen.com/ca/ca/config/accountapi.shtml?

We're using this and it looks fine
`https://[YOUR_LIVE_PREFIX]-checkout-live.adyenpayments.com/checkout/v67/originKeys`

Question: v1 or v67?

Request: Possible to add this to the URLs section?

Thanks

**Comment by wboereboom** [comment]
Hey @BerkanCetinkayaOSF,

Thanks for reaching out.
The list you referred to does indeed not list all our API endpoints.
A full list can be found in our [API docs](https://docs.adyen.com/api-explorer/).
I hope that clarifies things.

Kind Regards,
Wouter
Adyen

**Comment by BerkanCetinkayaOSF** [comment]
> Hey @BerkanCetinkayaOSF,
> 
> Thanks for reaching out.
> The list you referred to does indeed not list all our API endpoints.
> A full list can be found in our [API docs](https://docs.adyen.com/api-explorer/).
> I hope that clarifies things.
> 
> Kind Regards,
> Wouter
> Adyen

yes, I'm asking why it's not listed?

**Comment by wboereboom** [comment]
Closing this issue as this is outside the scope of this repository. 
This question was addressed directly through our Implementation Manager.
