### ISSUE TITLE
HMAC Endpoint Activation

### ISSUE THREAD

**Issue by oreillygshane** [Adyen/adyen-salesforce-commerce-cloud#566]
**Describe the bug**
HMAC key support is not available in the cartridge

**To Reproduce**
The Cartridge doesn't allow for HMAC endpoint configuations

**Comment by boby-bptech** [comment]
Hello @maassenbas 
HMAC key has been generated from adyen for standard  notification setup, however there is no option in sfcc adyen preference to store it and also in code I cannot see it really used. Please suggest are you supporting HMAC key with SFCC communications

**Comment by oreillygshane** [comment]
@maassenbas do you have any ideas on the above? Thanks!

**Comment by wboereboom** [comment]
Hi @boby-bptech , @oreillygshane,

Our cartridge does not support HMAC key for notifications at this time.
Currently only basic authentication is supported as described in our [documentation](https://docs.adyen.com/plugins/salesforce-commerce-cloud/set-up-the-cartridge#step-5-receive-payment-status-updates).

Kind regards,
Wouter
Adyen

**Comment by olga-adyen** [comment]
Hi @oreillygshane 
We will release a new version with HMAC validation beginning of Q3. Therefore i will close this issue. Thank you!
