### ISSUE TITLE
AdyenRecurringEnabled is still present in Adyen attribute group

### ISSUE THREAD

**Issue by mag-spinup-digital** [Adyen/adyen-salesforce-commerce-cloud#569]
**Describe the bug**
"AdyenRecurringEnabled" is still present in the "group-definitions" in "SitePreferences" within the "system-objecttype-extensions.xml" file.
Release "21.2.0" had this update https://github.com/Adyen/adyen-salesforce-commerce-cloud/pull/468 , but the "AdyenRecurringEnabled" was not removed from the "Adyen" attribute group.

**To Reproduce**
1. Do a Site Import and see the data error
```
[2021-10-22 06:56:21.062 GMT] WARN [DATAERROR] Line: 308/System Type: SitePreferences: Attribute 'AdyenRecurringEnabled' referenced by group 'Adyen' is not defined. Skipping attribute assignment.

```

**Comment by wboereboom** [comment]
This issue was addressed in #590
