### ISSUE TITLE
Credit Card - "Name on card" field not validated on submission

### ISSUE THREAD

**Issue by ta-benhon** [Adyen/adyen-salesforce-commerce-cloud#583]
**Describe the bug**
When submitting the credit card form, the "Name on card" input field is not validated. Upon submission, the Web Developer Tools' console provides the following error: `TypeError: e is null`. The error points to a line in the `bundle.js` (see screenshot).

**To Reproduce**
1. Go to the payment section
2. Leave the "name on card" field (or all fields) empty
3. Submit payment
4. See error in console

**Expected behavior**
"Name on card" to be properly validated upon submission.

**Screenshots**
![image](https://user-images.githubusercontent.com/45342097/141885623-cf2c1e86-91ed-48be-8f93-fe7508f508c5.png)
![image](https://user-images.githubusercontent.com/45342097/141885681-0a1826e1-cf97-4479-958f-33f96e634e3f.png)

**Additional context**
`link_adyen` cartridge version: 21.1.0

This particular issue was resolved in version 4.7.3 of `adyen-web`: https://github.com/Adyen/adyen-web/releases/tag/v4.7.3

_Side-note_: when submitting an invalid form, the Checkout-SubmitPayment request is fired regardless. Is there an item on the roadmap to prevent this or is this expected behaviour?

**Comment by wboereboom** [comment]
Hi @ta-benhon,

Thank you for raising this issue.
We make sure to update our web-component on every release, so this issue will be solved as soon as we make our next release (no ETA as of yet, I apologize).

Regarding your side-note: This seems to be a bug that only occurs when you've not filled in any field on the web-component. I'll make a note to look into it. Fortunately. we do not expect this to result in any serious errors or payment disruptions, but this should not happen. 

Kind regards,
Wouter
Adyen
