### ISSUE TITLE
Card Number is not valid on payment edit

### ISSUE THREAD

**Issue by soerensiegjensen** [Adyen/adyen-salesforce-commerce-cloud#601]
**Describe the bug**
When editing prefilled payment detail during the check process, it is not valid before chancing the card number.

**To Reproduce**
1. Go through the order process and enter vaild payment informations
2. At the placeOrder stage, press edit on payment detail
3. You are taken back to the payment stage
4. The form is filled out with all the payment details
5. Confirm again without editing the payment details and nothing happens.
6. The browser developer tools shows that a call is made to "CheckoutServices-SubmitPayment" but the response includes this: fieldErrors: [{dwfrm_billing_creditCardFields_cardNumber: "Please enter the Number as it appears on your card"}]
7. Delete just one number from the prefilled card number and write it again
8. Confirm again and you are taken to the placeOrder stage.

**Expected behavior**
When editing the payment details it should be possible to confirm without having to edit the card number. It works correctly for the expiration date and CVC.

**Desktop (please complete the following information):**
 - OS: MacOS 12.0.1
 - Browser: Chrome
 - Version: 96.0.4664.93

**Comment by wboereboom** [comment]
Hi @soerensiegjensen,

Thank you for raising this issue.
I was not able to reproduce your issue with our latest cartridge version. 
What cartridge version are you experiencing this issue on?

Kind regards,
Wouter
Adyen

**Comment by soerensiegjensen** [comment]
Hi @wboereboom 

Thanks for a fast reply.
I am running on v20.1.3. I know it is not the newest version, but would like to wait until after the holiday season with updating. Could this issue have been fixed with PR #538? Because that would be easy to fix in my version of the Adyen Cartridge. If not, could you point me to the possible fix?

Best regards
Søren

**Comment by maassenbas** [comment]
Hi @soerensiegjensen ,

I've been trying to reproduce the issue, but it seems to work fine if I reproduce the steps you listed above.
I tested it on my side with v20.1.3 and SFRA version 5.3.0. 
Which SFRA version did you test it with? 

Thanks,
Bas Maassen
Adyen

**Comment by soerensiegjensen** [comment]
Hi @maassenbas,

Thanks for the update. I am running on SFRA 5.1.0.

Thanks
Søren

**Comment by soerensiegjensen** [comment]
Hi @maassenbas,

Just following up on this. Were you able to see a possible solution?

Thanks
Søren

**Comment by zaiddreakh** [comment]
Hey @soerensiegjensen,

Apologies for the late reply. @maassenbas is currently on leave.
We're still not able to reproduce the problem on our test sandboxes. Could you please share a screen recording of what happens? I will also try to reproduce it on older SFRA versions and see.

Regards,
Zaid
Adyen
