### ISSUE TITLE
Card holder name is validated by client side scripts instead of Adyen due to 'required' attribute in code

### ISSUE THREAD

**Issue by johns-abraham-borngroup** [Adyen/adyen-salesforce-commerce-cloud#617]
**Describe the bug**
We are getting an odd error messages for card holder name field.

When we set card holder name (holderNameRequired = true) the Card Holder name input field is rendering with 'required' attribute unlike card number field, cvv field, expiry date field etc.
Due to this 'required' attribute the client side code dong a validation on that required field even before Adyen does the same.

Please note that, if we remove the 'required' attribute it will work as expected.

**To Reproduce**
Enabled Card holder name from BM, set holderNameRequired = true

**Expected behavior**
The field should be validated by Adyen instead of client side scripts, 

**Screenshots**
![image](https://user-images.githubusercontent.com/77099234/149935613-6523d05e-2f64-4ec0-8d2b-094f97bf72f5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 97

**Additional context**

**Comment by wboereboom** [comment]
Hi @johns-abraham-borngroup,

Thanks for raising this issue.
We are using the Adyen-Component to render out payment methods, and hence do not manage the UI and Validation on the specific component-related fields.

You can raise this issue here: https://github.com/Adyen/adyen-web/issues in order to request this feature.

Kind Regards,
Wouter
Adyen

**Comment by johns-abraham-borngroup** [comment]
Thanks Wouter,

Raised the issue on adyen-web git repo.
Ref: https://github.com/Adyen/adyen-web/issues/1452

Regards,
Johns

**Comment by wboereboom** [comment]
No problem at all. 
Apologies for having to bounce your request around.

Regards,
Wouter
Adyen
