### ISSUE TITLE
Condition never could be resolved in the Adyen Job ==> email notification send in wrong case

### ISSUE THREAD

**Issue by NicolasRoche-fr** [Adyen/adyen-salesforce-commerce-cloud#653]
**Describe the bug**
When the job process run,  the condition in the file .\cartridges\int_adyen_overlay\cartridge\scripts\handleCustomObject.js#115
`       if (order.paymentStatus === Order.PAYMENT_STATUS_PAID) {`
is never accepted because 

- order.paymentStatus is a string like PAID
- Order.PAYMENT_STATUS_PAID is a number 1, 2 or 3 [order class](https://documentation.b2c.commercecloud.salesforce.com/DOC3/index.jsp?topic=%2Fcom.demandware.dochelp%2FDWAPI%2Fscriptapi%2Fhtml%2Fapi%2Fclass_dw_order_Order.html)

**To Reproduce**
1. Custom object adyenNotification is fill with record in process status
2. run the job Adyen Process
3. the order can be updated to PAID status even if the satus is allready in this status and an email is sent

**Expected behavior**
the code must be enter in the conditon : 
`        if (order.paymentStatus === Order.PAYMENT_STATUS_PAID) {
            Logger.getLogger('Adyen', 'adyen').info('Duplicate callback received for order {0}.', order.orderNo);`        

and finally we always enter in the final condition even if the initial status of the order is PAID (2) : 

`   if (customObj.custom.success === 'true') {
          var amountPaid = parseFloat(order.custom.Adyen_value) + parseFloat(customObj.custom.value);
          var totalAmount = adyenHelper.getCurrencyValueForApi(adyenPaymentInstrument.getPaymentTransaction().getAmount()).value;

          if (order.paymentStatus === Order.PAYMENT_STATUS_PAID) {
            Logger.getLogger('Adyen', 'adyen').info('Duplicate callback received for order {0}.', order.orderNo);
          } else if (amountPaid < totalAmount) {
            order.setPaymentStatus(Order.PAYMENT_STATUS_PARTPAID);
            Logger.getLogger('Adyen', 'adyen').info('Partial amount {0} received for order number {1} with total amount {2}', customObj.custom.value, order.orderNo, totalAmount);
          } else {
            order.setPaymentStatus(Order.PAYMENT_STATUS_PAID);
            order.setExportStatus(Order.EXPORT_STATUS_READY);
            order.setConfirmationStatus(Order.CONFIRMATION_STATUS_CONFIRMED);
            Logger.getLogger('Adyen', 'adyen').info('Order {0} updated to status PAID.', order.orderNo);
            result.SubmitOrder = true;
          }
`

the right condition could be : 
`        if (order.getPaymentStatus()=== Order.PAYMENT_STATUS_PAID) { `

**Comment by wboereboom** [comment]
Hi @NicolasRoche-fr ,

Thanks for raising this issue!
You are absolutely right.

We are aware of this issue and have since fixed it for our upcoming release (22.1.0).
The updated code can be found [here](https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/develop/src/cartridges/int_adyen_overlay/cartridge/scripts/handleCustomObject.js#L130)

Your proposed solution should indeed also work.

Kind Regards,
Wouter
Adyen
