### ISSUE TITLE
Adyen 3D Secure 2 bug

### ISSUE THREAD

**Issue by asuciu-gpsw** [Adyen/adyen-salesforce-commerce-cloud#689]
**Describe the bug**
Sometimes, the 3DSecure 2 flow breaks due to a JS error in _adyen3ds2.isml_ template (https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/main/cartridges/int_adyen_overlay/cartridge/templates/default/threeds2/adyen3ds2.isml). The _handleOnAdditionalDetails_ function tries to set the value of a DOM element (_document.getElementById("stateData").value = JSON.stringify(state.data);_) which is not loaded yet. 

**To Reproduce**
Try to place an order using 3DS Secure 2 CC (e.g. 3714 4963 5398 431). Sometimes, a white page is displayed due to the above error.

**Expected behavior**
Adyen 3DSecure 2 flow is not interrupted by a JS error.

**Screenshots**
<img width="541" alt="Screen Shot 2022-08-19 at 1 27 52 PM" src="https://user-images.githubusercontent.com/83227631/185604310-8a477c2f-8f0c-4f39-97f3-4b43116d759c.png">

**Comment by maassenbas** [comment]
Hi @asuciu-gpsw ,
Thanks for reaching out. 
We will investigate the issue and create an internal ticket for it.
We will update you once we have more findings. 

Kind regards,
Bas Maassen
Adyen
