### ISSUE TITLE
Paypal - Wrong billing address on the order when it terminates early

### ISSUE THREAD

**Issue by dbellemogithub** [Adyen/adyen-salesforce-commerce-cloud#716]
**Describe the bug**
When you pay with Paypal sometimes the order hasn't the billing address fields of the checkout. It happens when an user clicks on the yellow button of Paypal and doesn't pass the fields validation (for example he wrongs the phone field insterting some letters). So after the correct compilation of the the missing/wrong fields, the user clicks again over the yellow button of Paypal, place the order and the billing address is not correctly compiled with the last info.

**To Reproduce**
1. Go to the second step of checkout
2. Empty the address1 field
3. Click on paypal yellow button
4. See error validation
5. Fill the address1 field with a different value than the shipping address one
6. Click on paypal yellow button
7. Place the order
8. Check on the order section: the address1 is equal to the address1 of shipping address

**Expected behavior**
The address1 should be equal to the address1 of billingAddress and not to the shippingAddress one

**Comment by dbellemogithub** [comment]
The solution is to add this snippet inside cartridges\int_adyen_SFRA\cartridge\client\default\js\adyenCheckout.js: 
![immagine](https://user-images.githubusercontent.com/53867305/198055011-d3e2c903-8c2c-41b8-9508-fc933e0277ed.png)

**Comment by zaiddreakh** [comment]
Hey @dbellemogithub,
Thanks for raising this issue. I have brought it to the attention of the relevant team and will come back to you ASAP.
Cheers,
Zaid
Adyen
