### ISSUE TITLE
Returning from Sofort Bank is hitting Order-Confirm twice

### ISSUE THREAD

**Issue by evechey** [Adyen/adyen-salesforce-commerce-cloud#764]
**Describe the bug**
On our development realm, when a user chooses Sofort they are taken to the Sofort Test Bank Portal. After confirming their details, they are redirected back to the SFCC storefront via Order-Confirm. This route is being hit twice though which sometimes results in an error.

**To Reproduce**
1. Go to a SFCC storefront with Sofort as an Adyen payment option
2. Select Sofort, and confirm the details on the Sofort portal
3. When returning to the SFCC storefront, see that Order-Confirm is getting hit twice.

**Expected behavior**
Order-Confirm is only being hit once.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome 
 - Version Version 108.0.5359.99 (Official Build) (64-bit)

**Comment by zaiddreakh** [comment]
Hey @evechey, thanks for opening this issue. 
Could you please share with us the cartridge version that you are on? So we can try to reproduce this on the same version.
Thanks,
Zaid
Adyen
