### ISSUE TITLE
state data is not comming on ajax call

### ISSUE THREAD

**Issue by bhagyesh910** [Adyen/adyen-salesforce-commerce-cloud#766]
**Describe the bug**
When we are place the order on payment page but we didn't get any kind of statedata from the client side.
could you please help us for this issue.
We are using adyen version : 21.2.0
sfra version : 4.4.0

function assignPaymentMethodValue() {
  var adyenPaymentMethod = document.querySelector('#adyenPaymentMethodName') ? document.querySelector('#adyenPaymentMethodName') : store.selectedMethod; // if currently selected paymentMethod contains a brand it will be part of the label ID

  var paymentMethodlabelId = store.brand ? "#lb_".concat(store.selectedMethod, "_").concat(store.brand) : "#lb_".concat(store.selectedMethod);
  adyenPaymentMethod.value = document.querySelector(paymentMethodlabelId).innerHTML;
}

**Additional context**
we are using one page checout so we are place order without any page load so it's not working and when we are reload the page then it's working good .

Thanks ,
Bhagyesh

**Comment by wboereboom** [comment]
Hi @bhagyesh910 ,
Our plugin only supports SFRA v5.x.x or v6.x.x.
Could you please upgrade and see if the problem persists?

Kind Regards,
Wouter
Adyen

**Comment by bhagyesh910** [comment]
HI, @wboereboom could you tell me the bug for SFRA 4.3.x and 4.4.x  for this Adyen cartridge version?

in README.md file given the broken link: https://github.com/SalesforceCommerceCloud/storefront-reference-architecture/pull/797

So could you provide the bug link?

Regards,
Bhagyesh

**Comment by wboereboom** [comment]
Hi @bhagyesh910,

The link is correct. you will need to create a SalesForce account and request access to the SalesforceCommerceCloud GitHub Org as described [here](https://trailhead.salesforce.com/content/learn/modules/b2c-developer-resources-and-tools/b2c-developer-access-repositories)

Kind Regards,
Wouter
Adyen

**Comment by bhagyesh910** [comment]
Thanks For your support @wboereboom
