### ISSUE TITLE
Exception occurred during request processing: ScriptingException TypeError: Cannot call method "indexOf" of null (int_adyen/cartridge/scripts/adyenRedirectVerificationSHA256.ds#162)

### ISSUE THREAD

**Issue by kirill-kostiuk** [Adyen/adyen-salesforce-commerce-cloud#85]
https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/fdbe9f9f88accb4dba6e6e679f04afcdcba54fdc/cartridges/int_adyen/cartridge/scripts/adyenRedirectVerificationSHA256.ds#L162

**Comment by maassenbas** [comment]
Hi @kirill-kostiuk ,
Could you make sure you imported the metadata? 
See here: https://docs.adyen.com/developers/plug-ins-and-partners/salesforce-commerce-cloud/integrating-a-cartridge/set-up#metadataimport

**Comment by kirill-kostiuk** [comment]
Hi @maassenbas, yes I've imported all necessary metadata.
