### ISSUE TITLE
Function isOpenInvoiceMethod

### ISSUE THREAD

**Issue by asuciu-gpsw** [Adyen/adyen-salesforce-commerce-cloud#855]
**Describe the bug**
The current implementation of _isOpenInvoiceMethod_ function from _cartridges/int_adyen_overlay_core/cartridge/scripts/util/adyenHelper.js_ is:
`  isOpenInvoiceMethod: function isOpenInvoiceMethod(paymentMethod) {
    if (paymentMethod.indexOf('afterpay') - 1 || paymentMethod.indexOf('klarna') > -1 || paymentMethod.indexOf('ratepay') > -1 || paymentMethod.indexOf('facilypay') > -1 || paymentMethod === 'zip' || paymentMethod === 'affirm' || paymentMethod === 'clearpay') {
      return true;
    }
    return false;
  }`,
  so it returns _true_ almost every time

**Expected behavior**
The function should properly check the paymentMethod:
`isOpenInvoiceMethod: function isOpenInvoiceMethod(paymentMethod) {
    if (paymentMethod.indexOf('afterpay') > - 1 || paymentMethod.indexOf('klarna') > -1 || paymentMethod.indexOf('ratepay') > -1 || paymentMethod.indexOf('facilypay') > -1 || paymentMethod === 'zip' || paymentMethod === 'affirm' || paymentMethod === 'clearpay') {
      return true;
    }
    return false;
  }`

**Comment by amihajlovski** [comment]
Hello @asuciu-gpsw, 

I see there is a typo when checking one of the payment methods, we will fix it and include in the next release. 

Thanks for pointing this out
Aleksandar
Adyen
