### ISSUE TITLE
Exception occurred during request processing: ScriptingException TypeError: Cannot set property "value" of undefined to "123" (app_storefront_base/cartridge/controllers/CheckoutServices.js#235)

### ISSUE THREAD

**Issue by gauravarora8** [Adyen/adyen-salesforce-commerce-cloud#88]
This is happening as CheckoutServices-SubmitPayment in LINK_adyen cartridge is modifying viewData.paymentInformation which doesn't contain securityCode that was set at line no. 91 in CheckoutServices.js in base cartridge. This is accessed again at line no. 235 in base cartridge which is executed after the code in LINK_adyen cartridge as the code snippet is executed inside 'route:BeforeComplete'.

**Comment by maassenbas** [comment]
Hi @gauravarora8, 

The viewData.paymentInformation does contain the securityCode now if you look into our newest release. Could you confirm that this issue has been resolved? 

Thanks,
Bas

**Comment by gauravarora8** [comment]
This has been fixed now. Thanks Bas
