### ISSUE TITLE
Incorrect URLs in SFRA when pipeline alias for Checkout-Begin exists

### ISSUE THREAD

**Issue by clstopher** [Adyen/adyen-salesforce-commerce-cloud#907]
**Describe the bug**
If you create a pipeline alias for "Checkout-Begin" (eg, "checkout"), then AJAX requests for "Adyen-Sessions" and "Adyen-PaymentsDetails" fail because they go to the wrong endpoint.

**To Reproduce**
1. Install / Setup cartridge
2. In BM for the site, go to Merchant Tools > SEO > URL Rules. Click the "Pipeline URLs" tab. Add a new pipeline alias like "checkout" resolves to "Checkout-Begin".
3. Go to the site, add a product to your basket and proceed to the "Payment" step of checkout.
4. See that the Payments web component doesn't render, and in Dev Console / Network tab, see that the Adyen-Sessions request resulted in a 500.
5. After fixing Adyen-Sessions (see below), note that you'll get a later failure if you go through a 3DS flow, after entering your password the modal will not close and you can see that Adyen-PaymentsDetails request returned a 500.

**Expected behavior**
Adding a pipeline alias for checkout should be allowed and payments should still be possible when one is defined.

**Screenshots**
None provided now.

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Additional context**
I suspect the same issue exists in SG Controllers, but have not tested.

This is because some of the client-side JS uses the simple relative URL of "Adyen-Sessions" and "Adyen-PaymentsDetails" without using URLUtils to generate actual / full URLs for these endpoints. A couple examples in the code here:

* https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/040c1f64218f7c3ca1529dc3779542220a609ca4/src/cartridges/int_adyen_SFRA/cartridge/client/default/js/adyenAccount.js#L38
* https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/8dd62a268c9e813cf323f128400161a9d93d4fa4/src/cartridges/int_adyen_SFRA/cartridge/client/default/js/adyen_checkout/checkoutConfiguration.js#L251
* https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/8dd62a268c9e813cf323f128400161a9d93d4fa4/cartridges/int_adyen_SFRA/cartridge/client/default/js/adyen_checkout/checkoutConfiguration.js#L255
* https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/8dd62a268c9e813cf323f128400161a9d93d4fa4/src/cartridges/int_adyen_SFRA/cartridge/client/default/js/commons/index.js#L19

A solution exists without changing code - Defining pipeline aliases for these two endpoints that are like "Adyen-Sessions" resolves to "Adyen-Sessions" and "Adyen-PaymentsDetails" resolves to "Adyen-PaymentsDetails".

**Comment by olga-adyen** [comment]
Hi @clstopher 
We are investigating this case internally. 

I'll close this issue once the feature is released.
