### ISSUE TITLE
ApplePayExpress error  "environment undefined "

### ISSUE THREAD

**Issue by zero-ims** [Adyen/adyen-salesforce-commerce-cloud#922]
Error reported when using ApplePayExpress on the shipping cart page

`VM11051 applePayExpress.js:16 Uncaught TypeError: Cannot read properties of undefined (reading 'environment')`

![image](https://github.com/Adyen/adyen-salesforce-commerce-cloud/assets/124959154/1c36a81d-000a-4579-b0c6-b15512d14dcf)

![image](https://github.com/Adyen/adyen-salesforce-commerce-cloud/assets/124959154/0f046b89-d0cb-43d2-b923-10e2523503e7)

I found out that window.Configuration is an undefined ;

Because only when the result of `${request.getHttpQueryString() && request.getHttpQueryString().indexOf('amazonCheckoutSessionId') > -1}` is true, the window.Configuration object will be output

![image](https://github.com/Adyen/adyen-salesforce-commerce-cloud/assets/124959154/b1b0ff15-49ca-4c9c-bef3-f578bdc66384)

Does anyone know how to deal with this problem?

**Comment by zenit2001** [comment]
Hi @zero-ims  ,

Thanks for reaching out.
Which version of the cartridge are you using?

Thanks,
Zenit Shkreli
Adyen

**Comment by amihajlovski** [comment]
Hello @zero-ims 

This is now fixed in the latest release

Kind Regards
Aleksandar
Adyen
