### ISSUE TITLE
AdyenCheckout is not defined error

### ISSUE THREAD

**Issue by davidlinke** [Adyen/adyen-salesforce-commerce-cloud#928]
**Describe the bug**

I'm trying to upgrade our cartridges to the latest 23.2.0 version and am running into a client-side js error `ReferenceError: AdyenCheckout is not defined at renderGenericComponent.js`. I can't find anywhere in the cartridges where `AdyenCheckout` is defined; it was previously defined in our older cartridge in `bundle.js`.

**To Reproduce**
1. Go to the payment step in checkout
2. Observe Adyen component does not render and see above error in console

**Expected behavior**
Adyen component renders without errors

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Comment by amihajlovski** [comment]
Hello @davidlinke,

Looks like the Adyen checkout script is not loaded correctly on your side. 
[On this line](https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/main/src/cartridges/int_adyen_SFRA/cartridge/templates/default/checkout/billing/adyenComponentForm.isml#L9) we are loading the script.
Can you check if you get any errors in console and provide some screenshots?

Thanks in advance
Aleksandar
Adyen

**Comment by davidlinke** [comment]
Thanks for your insights @amihajlovski. Turns out at the line you linked, `pdict.AdyenHelper` did not exist and was returning null, so I had to add `viewData.AdyenHelper = AdyenHelper;` to  `int_adyen_SFRA/cartridge/controllers/middlewares/checkout/begin.js` to get it to work

**Comment by amihajlovski** [comment]
Happy to help!

I will close this issue and if anything pops up in future please open a new one.

Kind Regards,
Aleksandar
Adyen
