### ISSUE TITLE
Incorrect documentation for Business Manager Cartridges

### ISSUE THREAD

**Issue by KennethRobbeFrucon** [Adyen/adyen-salesforce-commerce-cloud#931]
**Describe the bug**
The [documentation](https://docs.adyen.com/plugins/salesforce-commerce-cloud/set-up-the-cartridge#set-up-the-business-manager) no longer instructs you to add `bm_adyen` to the cartridge path of Business Manager. However, as this cartridge is responsible for registering the custom **Adyen settings** BM module, this doesn't happen and you can't proceed with the next configuration steps.

**Screenshots**
![image](https://github.com/Adyen/adyen-salesforce-commerce-cloud/assets/34708318/afb8363a-807b-4417-9504-7bad15ee8c67)

**Comment by amihajlovski** [comment]
Hello @KennethRobbeFrucon 

It is already solved and it is in our documentation, thanks for noticing
https://docs.adyen.com/plugins/salesforce-commerce-cloud/set-up-the-cartridge#set-up-the-business-manager

Kind Regards
Aleksandar
Adyen
