### ISSUE TITLE
User lands on empty cart after return from HPP

### ISSUE THREAD

**Issue by KennethRobbeFrucon** [Adyen/adyen-salesforce-commerce-cloud#932]
**Describe the bug**
User can land on an empty cart when they return from a HPP (e.g. when paying with EPS) when they click the "Continue"-button at the same time that the page is refreshing:

![image](https://github.com/Adyen/adyen-salesforce-commerce-cloud/assets/34708318/5901ea71-4310-45d4-9e9b-a79e7a85f2ee)

This triggers a duplicate request to Adyen-ShowConfirmation in the background:

![image](https://github.com/Adyen/adyen-salesforce-commerce-cloud/assets/34708318/1be4b39e-163e-45f9-9c82-4d77d15edcb7)

This means the logic inside this controller is executed twice. However, as it contains logic to not process the same order twice, the user is redirected to the cart page:
https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/c3737fcafe1898e74cf2639f477cf09848a75e11/cartridges/int_adyen_SFRA/cartridge/controllers/middlewares/adyen/showConfirmation.js#L64-L68

As their cart has already been converted to a placed order, it is empty.

**To Reproduce**
1. Place a payment with a payment method that redirects to a HPP (e.g. EPS)
2. Click the "Continue"-button before you're automatically redirected back.
3. Confirm that a duplicate request is triggered and you land on an empty cart page

**Expected behavior**
Users should still see the confirmation page even though their order has already been processed.

**Comment by amihajlovski** [comment]
Hello @KennethRobbeFrucon,

I tried the exact payment method (EPS) and for me it worked, the confirmation page is shown.
Which SFRA version are you trying?

Kind Regards
Aleksandar
Adyen
