### ISSUE TITLE
Not able to execute "npm run compile:js" successfully

### ISSUE THREAD

**Issue by kirill-kostiuk** [Adyen/adyen-salesforce-commerce-cloud#946]
I am trying to compile js for the last version of sfcc adyen integration, 23.2.0 and receive such erros during npm run compile:js:

ERROR in ./cartridges/int_adyen_SFRA/cartridge/client/default/js/adyenAccount.js 102:9
Module parse failed: Unexpected token (102:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     event.preventDefault();
|   } else {
>     card?.showValidation();
|   }
| });

ERROR in ./cartridges/int_adyen_SFRA/cartridge/client/default/js/adyen_checkout/helpers.js 10:53
Module parse failed: Unexpected token (10:53)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     adyenPaymentMethod.value = store.brand
|       ? store.brand
>       : document.querySelector(paymentMethodlabelId)?.innerHTML;
|   }
| }
 @ ./cartridges/int_adyen_SFRA/cartridge/client/default/js/adyenCheckout.js 13:4-39

ERROR in ./cartridges/int_adyen_SFRA/cartridge/client/default/js/adyen_checkout/checkoutConfiguration.js 122:27
Module parse failed: Unexpected token (122:27)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     renderAddedGiftCard(card);
|   });
>   if (store.addedGiftCards?.length) {
|     showGiftCardInfoMessage();
|   }
 @ ./cartridges/int_adyen_SFRA/cartridge/client/default/js/adyenCheckout.js 8:4-53

ERROR in ./cartridges/int_adyen_SFRA/cartridge/client/default/js/amazonPayExpressPart1.js 37:6
Module parse failed: Unexpected token (37:6)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     const amazonPayConfig = paymentMethodsResponse.find(
|       (pm) => pm.type === AMAZON_PAY,
>     )?.configuration;
|     if (!amazonPayConfig) return;
|

ERROR in ./cartridges/int_adyen_SFRA/cartridge/client/default/js/checkout/billing.js 38:55
Module parse failed: Unexpected token (38:55)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
| function updatePaymentInformation(order) {
>   if (order.billing.payment.selectedPaymentInstruments?.length) {
|     const selectedPaymentInstrument =
|       order.billing.payment.selectedPaymentInstruments[0];
 @ ./cartridges/int_adyen_SFRA/cartridge/client/default/js/checkout.js 5:16-45

ERROR in ./cartridges/int_adyen_SFRA/cartridge/store/index.js 4:19
Module parse failed: Unexpected token (4:19)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| class Store {
>   MASKED_CC_PREFIX = '************';
|
|   @observable checkout;
 @ ./cartridges/int_adyen_SFRA/cartridge/client/default/js/adyenCheckout.js 1:14-39

ERROR in ./cartridges/int_adyen_SFRA/cartridge/client/default/js/commons/index.js 57:9
Module parse failed: Unexpected token (57:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|       document
|         .getElementById('express-loader-container')
>         ?.classList.add('hidden');
|       document.getElementById('express-container')?.classList.remove('hidden');
|     }
 @ ./cartridges/int_adyen_SFRA/cartridge/client/default/js/expressPaymentMethodsVisibility.js 1:42-62

ERROR in ./cartridges/int_adyen_SFRA/cartridge/client/default/js/amazonPayCheckout.js 6:40
Module parse failed: Unexpected token (6:40)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| function handleAuthorised(response) {
|   document.querySelector('#result').value = JSON.stringify({
>     pspReference: response.fullResponse?.pspReference,
|     resultCode: response.fullResponse?.resultCode,
|     paymentMethod: response.fullResponse?.paymentMethod

ERROR in ./cartridges/int_adyen_SFRA/cartridge/client/default/js/applePayExpress.js 81:40
Module parse failed: Unexpected token (81:40)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   resolveApplePay();
|   document.querySelector('#result').value = JSON.stringify({
>     pspReference: response.fullResponse?.pspReference,
|     resultCode: response.fullResponse?.resultCode,
|     paymentMethod: response.fullResponse?.paymentMethod

ERROR in ./cartridges/int_adyen_SFRA/cartridge/client/default/js/adyen_checkout/renderGenericComponent.js 92:29
Module parse failed: Unexpected token (92:29)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|       renderAddedGiftCard(card);
|     });
>     if (store.addedGiftCards?.length) {
|       showGiftCardInfoMessage();
|     }
 @ ./cartridges/int_adyen_SFRA/cartridge/client/default/js/adyenCheckout.js 4:4-54

**Comment by amihajlovski** [comment]
Hello @kirill-kostiuk 

I managed to compile the code using `node v18.12.0` and `npm v8.19.1`
Can you check your node an npm versions?

Kind Regards
Aleksandar 
Adyen

**Comment by amihajlovski** [comment]
Hello @kirill-kostiuk 

I just checked with `node v14.21.3` and it is being compiled. 
<img width="1440" alt="image" src="https://github.com/Adyen/adyen-salesforce-commerce-cloud/assets/6888241/83cc4bbd-6b04-4313-9343-1522e19ff104">

We use this command on a daily basis in order to deploy our code so we would've experience this during development.
Can you maybe reinstall the node dependencies?

Kind Regards
Aleksandar
Adyen

**Comment by kirill-kostiuk** [comment]
Hello @amihajlovski ,
I reinstalled node dependencies and issue is fixed.
Thanks for support!
