### ISSUE TITLE
Adyen Payment Integration (Path Error)

### ISSUE THREAD

**Issue by PrinceGOC** [Adyen/adyen-salesforce-commerce-cloud#947]
Hello
I'm working on Adyen Payment integration with SFRA and I get this path errors : -
Here I attached the path setting and error of my code and you also can see the folder structure.
If anyone have the solution then help me in this..
Because without the proper path, this files will not render on storefront.

![Screenshot (182)](https://github.com/Adyen/adyen-salesforce-commerce-cloud/assets/131000840/8a855d02-fe46-4ce5-a119-4a8e60f0bec4)
![Screenshot (183)](https://github.com/Adyen/adyen-salesforce-commerce-cloud/assets/131000840/b9ff06a7-51d7-4220-b8c7-0a5e659551b4)

**Comment by amihajlovski** [comment]
Hello @PrinceGOC 

Our `base` path in package.json is defined like this https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/main/package.json#L7
Can you check if that would work?
Also please check if you have the `base` module installed in the node_modules directory.

Kind Regards
Aleksandar
Adyen

**Comment by PrinceGOC** [comment]
Yes I tried the mentioned path in given link. But my folder structure is different so I need to change it accordingly.

Also the base module is installed in my node_modules directory.

**Comment by PrinceGOC** [comment]
Additionally I tried mentioned path and structure, but it emitted the files which do not match the the path.

`PS E:\GOC Projects\Commerce Cloud Projects\goc-task> npm run swb:dev

> goc-task@1.0.0 swb:dev E:\GOC Projects\Commerce Cloud Projects\goc-task
> node ./node_modules/sfra-webpack-builder/webpackHandling/webpack.js --config ./node_modules/sfra-webpack-builder/webpack.config.js --env dev

bundleCartridge ./storefront-reference-architecture/cartridges/app_storefront_base fileType clean
bundleCartridge ./storefront-reference-architecture/cartridges/app_storefront_base fileType jsx
Entry not found - please check if jsx folder exist in your cartridge : ./storefront-reference-architecture/cartridges/app_storefront_base
bundleCartridge ./storefront-reference-architecture/cartridges/app_storefront_base fileType js
bundleCartridge ./storefront-reference-architecture/cartridges/app_storefront_base fileType scss
bundleCartridge ./storefront-reference-architecture/cartridges/app_storefront_base fileType copy
bundleCartridge ./adyen-salesforce-commerce-cloud/cartridges/int_adyen_SFRA fileType clean
bundleCartridge ./adyen-salesforce-commerce-cloud/cartridges/int_adyen_SFRA fileType jsx
Entry not found - please check if jsx folder exist in your cartridge : ./adyen-salesforce-commerce-cloud/cartridges/int_adyen_SFRA
bundleCartridge ./adyen-salesforce-commerce-cloud/cartridges/int_adyen_SFRA fileType js
bundleCartridge ./adyen-salesforce-commerce-cloud/cartridges/int_adyen_SFRA fileType scss
Entry not found - please check if scss folder exist in your cartridge : ./adyen-salesforce-commerce-cloud/cartridges/int_adyen_SFRA
bundleCartridge ./adyen-salesforce-commerce-cloud/cartridges/int_adyen_SFRA fileType copy
bundleCartridge ./adyen-salesforce-commerce-cloud/cartridges/int_adyen_overlay fileType clean
bundleCartridge ./adyen-salesforce-commerce-cloud/cartridges/int_adyen_overlay fileType jsx
Entry not found - please check if jsx folder exist in your cartridge : ./adyen-salesforce-commerce-cloud/cartridges/int_adyen_overlay
bundleCartridge ./adyen-salesforce-commerce-cloud/cartridges/int_adyen_overlay fileType js
Entry not found - please check if js folder exist in your cartridge : ./adyen-salesforce-commerce-cloud/cartridges/int_adyen_overlay
bundleCartridge ./adyen-salesforce-commerce-cloud/cartridges/int_adyen_overlay fileType scss
Entry not found - please check if scss folder exist in your cartridge : ./adyen-salesforce-commerce-cloud/cartridges/int_adyen_overlay
bundleCartridge ./adyen-salesforce-commerce-cloud/cartridges/int_adyen_overlay fileType copy
bundleCartridge ./adyen-salesforce-commerce-cloud/cartridges/bm_adyen fileType clean
bundleCartridge ./adyen-salesforce-commerce-cloud/cartridges/bm_adyen fileType jsx
Entry not found - please check if jsx folder exist in your cartridge : ./adyen-salesforce-commerce-cloud/cartridges/bm_adyen
bundleCartridge ./adyen-salesforce-commerce-cloud/cartridges/bm_adyen fileType js
Entry not found - please check if js folder exist in your cartridge : ./adyen-salesforce-commerce-cloud/cartridges/bm_adyen
bundleCartridge ./adyen-salesforce-commerce-cloud/cartridges/bm_adyen fileType scss
Entry not found - please check if scss folder exist in your cartridge : ./adyen-salesforce-commerce-cloud/cartridges/bm_adyen
bundleCartridge ./adyen-salesforce-commerce-cloud/cartridges/bm_adyen fileType copy
./storefront-reference-architecture/cartridges/app_storefront_base/clean:
  ./storefront-reference-architecture/cartridges/app_storefront_base/clean (webpack 5.75.0) compiled successfully in 677 ms

./storefront-reference-architecture/cartridges/app_storefront_base/js:
  assets by path default/js/*.js 1.02 MiB
    asset default/js/main.js 550 KiB [emitted] (name: default/js/main.js) 1 related asset
    + 18 assets
  assets by path default/js/components/*.js 203 KiB
    asset default/js/components/miniCart.js 61.5 KiB [emitted] (name: default/js/components/miniCart.js) 1 related asset
    + 16 assets
  assets by path default/js/checkout/*.js 290 KiB
    asset default/js/checkout/checkout.js 143 KiB [emitted] (name: default/js/checkout/checkout.js) 1 related asset
    asset default/js/checkout/billing.js 68.5 KiB [emitted] (name: default/js/checkout/billing.js) 1 related asset
    + 5 assets
  assets by path default/js/product/*.js 114 KiB
    asset default/js/product/quickView.js 41.1 KiB [emitted] (name: default/js/product/quickView.js) 1 related asset
    asset default/js/product/detail.js 39.4 KiB [emitted] (name: default/js/product/detail.js) 1 related asset
    asset default/js/product/base.js 33.6 KiB [emitted] (name: default/js/product/base.js) 1 related asset
  + 10 assets
  runtime modules 7.94 KiB 37 modules
  cacheable modules 693 KiB
    modules by path ./storefront-reference-architecture/cartridges/app_storefront_base/cartridge/client/default/js/ 233 KiB
      modules by path ./storefront-reference-architecture/cartridges/app_storefront_base/cartridge/client/default/js/*.js 17.4 KiB 19 modules
      modules by path ./storefront-reference-architecture/cartridges/app_storefront_base/cartridge/client/default/js/components/*.js 37.3 KiB 17 modules
      modules by path ./storefront-reference-architecture/cartridges/app_storefront_base/cartridge/client/default/js/checkout/*.js 85.4 KiB 7 modules
      modules by path ./storefront-reference-architecture/cartridges/app_storefront_base/cartridge/client/default/js/product/*.js 41.5 KiB 3 modules
      + 10 modules
    modules by path ./storefront-reference-architecture/node_modules/ 459 KiB
      modules by path ./storefront-reference-architecture/node_modules/lodash/*.js 15.5 KiB 14 modules
      modules by path ./storefront-reference-architecture/node_modules/bootstrap/js/src/*.js 85.8 KiB
        ./storefront-reference-architecture/node_modules/bootstrap/js/src/util.js 5.26 KiB [built] [code generated]
        + 6 modules
      ./storefront-reference-architecture/node_modules/cleave.js/dist/cleave-esm.js 44.3 KiB [built] [code generated]
      ./storefront-reference-architecture/node_modules/jquery/dist/jquery.js 314 KiB [built] [code generated]
  ./storefront-reference-architecture/cartridges/app_storefront_base/js (webpack 5.75.0) compiled successfully in 17757 ms

./storefront-reference-architecture/cartridges/app_storefront_base/scss:
  assets by path default/css/ 576 KiB
    assets by path default/css/experience/ 96.8 KiB 15 assets
    assets by path default/css/*.css 427 KiB
      asset default/css/global.css 374 KiB [emitted] (name: default/css/global.scssjs) 1 related asset
      + 7 assets
    assets by path default/css/account/*.css 18.7 KiB
      asset default/css/account/orderTrack.css 4.94 KiB [emitted] (name: default/css/account/orderTrack.scssjs) 1 related asset
      + 5 assets
    assets by path default/css/checkout/*.css 14.5 KiB
      asset default/css/checkout/checkout.css 12.9 KiB [emitted] (name: default/css/checkout/checkout.scssjs) 1 related asset
      asset default/css/checkout/checkoutLogin.css 1.61 KiB [emitted] (name: default/css/checkout/checkoutLogin.scssjs) 1 related asset
    asset default/css/product/detail.css 15.1 KiB [emitted] (name: default/css/product/detail.scssjs) 1 related asset
    asset default/css/skin/skin.css 4.44 KiB [emitted] (name: default/css/skin/skin.scssjs) 1 related asset
  asset fr_FR/css/account/addressBook.css 2.54 KiB [emitted] (name: fr_FR/css/account/addressBook.scssjs) 1 related asset
  asset it_IT/css/account/addressBook.css 2.54 KiB [emitted] (name: it_IT/css/account/addressBook.scssjs) 1 related asset
  runtime modules 41.4 KiB 175 modules
  orphan modules 1.64 MiB [orphan] 37 modules
  cacheable modules 532 KiB (css/mini-extract) 1.71 KiB (javascript)
    modules by path ./storefront-reference-architecture/cartridges/app_storefront_base/cartridge/client/default/scss/ 530 KiB (css/mini-extract) 1.61 KiB (javascript)
      css modules 530 KiB 34 modules
      javascript modules 1.61 KiB 33 modules
    modules by path ./storefront-reference-architecture/cartridges/app_storefront_base/cartridge/client/fr_FR/scss/account/*.scss 50 bytes (javascript) 1.21 KiB (css/mini-extract)
      ./storefront-reference-architecture/cartridges/app_storefront_base/cartridge/client/fr_FR/scss/account/addressBook.scss 50 bytes [built] [code generated]  
      css ./node_modules/sfra-webpack-builder/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[0].use[1]!./node_modules/sfra-webpack-builder/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[0].use[2]!./node_modules/sfra-webpack-builder/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[0].use[3]!./storefront-reference-architecture/cartridges/app_storefront_base/cartridge/client/fr_FR/scss/account/addressBook.scss 1.21 KiB [built] [code generated]
    modules by path ./storefront-reference-architecture/cartridges/app_storefront_base/cartridge/client/it_IT/scss/account/*.scss 50 bytes (javascript) 1.21 KiB (css/mini-extract)
      ./storefront-reference-architecture/cartridges/app_storefront_base/cartridge/client/it_IT/scss/account/addressBook.scss 50 bytes [built] [code generated]  
      css ./node_modules/sfra-webpack-builder/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[0].use[1]!./node_modules/sfra-webpack-builder/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[0].use[2]!./node_modules/sfra-webpack-builder/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[0].use[3]!./storefront-reference-architecture/cartridges/app_storefront_base/cartridge/client/it_IT/scss/account/addressBook.scss 1.21 KiB [built] [code generated]

  WARNING in ./storefront-reference-architecture/cartridges/app_storefront_base/cartridge/client/default/scss/global.scss (./storefront-reference-architecture/cartridges/app_storefront_base/cartridge/client/default/scss/global.scss.webpack[javascript/auto]!=!./node_modules/sfra-webpack-builder/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[0].use[1]!./node_modules/sfra-webpack-builder/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[0].use[2]!./node_modules/sfra-webpack-builder/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[0].use[3]!./storefront-reference-architecture/cartridges/app_storefront_base/cartridge/client/default/scss/global.scss)
  Module Warning (from ./node_modules/sfra-webpack-builder/node_modules/postcss-loader/dist/cjs.js):
  Warning

  (2723:3) autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.
   @ ./storefront-reference-architecture/cartridges/app_storefront_base/cartridge/client/default/scss/global.scss

  ./storefront-reference-architecture/cartridges/app_storefront_base/scss (webpack 5.75.0) compiled with 1 warning in 28279 ms

./storefront-reference-architecture/cartridges/app_storefront_base/copy:
  ERROR in unable to locate 'E:/GOC Projects/Commerce Cloud Projects/goc-task/node_modules/font-awesome/fonts/' glob

  ERROR in unable to locate 'E:/GOC Projects/Commerce Cloud Projects/goc-task/node_modules/flag-icon-css/flags' glob

  ./storefront-reference-architecture/cartridges/app_storefront_base/copy (webpack 5.75.0) compiled with 2 errors in 671 ms

./adyen-salesforce-commerce-cloud/cartridges/int_adyen_SFRA/clean:
  ./adyen-salesforce-commerce-cloud/cartridges/int_adyen_SFRA/clean (webpack 5.75.0) compiled successfully in 492 ms

./adyen-salesforce-commerce-cloud/cartridges/int_adyen_SFRA/js:
  assets by path default/js/*.js 2.06 MiB
    asset default/js/checkout.js 532 KiB [emitted] (name: default/js/checkout.js) 1 related asset
    asset default/js/adyenCheckout.js 345 KiB [emitted] (name: default/js/adyenCheckout.js) 1 related asset
    asset default/js/applePayExpress.js 261 KiB [emitted] (name: default/js/applePayExpress.js) 1 related asset
    + 7 assets
  assets by path default/js/adyen_checkout/*.js 1.79 MiB
    asset default/js/adyen_checkout/checkoutConfiguration.js 340 KiB [emitted] (name: default/js/adyen_checkout/checkoutConfiguration.js) 1 related asset        
    asset default/js/adyen_checkout/makePartialPayment.js 309 KiB [emitted] (name: default/js/adyen_checkout/makePartialPayment.js) 1 related asset
    asset default/js/adyen_checkout/renderGenericComponent.js 306 KiB [emitted] (name: default/js/adyen_checkout/renderGenericComponent.js) 1 related asset      
    + 6 assets
  assets by path default/js/checkout/*.js 971 KiB
    asset default/js/checkout/checkoutSFRA6.js 487 KiB [emitted] (name: default/js/checkout/checkoutSFRA6.js) 1 related asset
    asset default/js/checkout/checkoutSFRA5.js 479 KiB [emitted] (name: default/js/checkout/checkoutSFRA5.js) 1 related asset
    asset default/js/checkout/billing.js 4.21 KiB [emitted] (name: default/js/checkout/billing.js) 1 related asset
  asset default/js/commons/index.js 220 KiB [emitted] (name: default/js/commons/index.js) 1 related asset
  runtime modules 14.8 KiB 68 modules
  cacheable modules 634 KiB
    modules by path ./adyen-salesforce-commerce-cloud/ 501 KiB
      modules by path ./adyen-salesforce-commerce-cloud/cartridges/int_adyen_SFRA/cartridge/client/default/js/ 303 KiB 23 modules
      ./adyen-salesforce-commerce-cloud/cartridges/int_adyen_SFRA/cartridge/store/index.js 9.87 KiB [built] [code generated]
      ./adyen-salesforce-commerce-cloud/node_modules/mobx/dist/mobx.esm.js 188 KiB [built] [code generated]
    modules by path ./storefront-reference-architecture/ 132 KiB
      modules by path ./storefront-reference-architecture/cartridges/app_storefront_base/cartridge/client/default/js/checkout/*.js 85.4 KiB 7 modules
      modules by path ./storefront-reference-architecture/cartridges/app_storefront_base/cartridge/client/default/js/components/*.js 1.89 KiB
        ./storefront-reference-architecture/cartridges/app_storefront_base/cartridge/client/default/js/components/scrollAnimate.js 240 bytes [built] [code generated]
        + 2 modules
      ./storefront-reference-architecture/cartridges/app_storefront_base/cartridge/client/default/js/util.js 634 bytes [built] [code generated]
      ./storefront-reference-architecture/node_modules/cleave.js/dist/cleave-esm.js 44.3 KiB [built] [code generated]
  ./adyen-salesforce-commerce-cloud/cartridges/int_adyen_SFRA/js (webpack 5.75.0) compiled successfully in 17477 ms

./adyen-salesforce-commerce-cloud/cartridges/int_adyen_SFRA/copy:
  ./adyen-salesforce-commerce-cloud/cartridges/int_adyen_SFRA/copy (webpack 5.75.0) compiled successfully in 482 ms

./adyen-salesforce-commerce-cloud/cartridges/int_adyen_overlay/clean:
  ./adyen-salesforce-commerce-cloud/cartridges/int_adyen_overlay/clean (webpack 5.75.0) compiled successfully in 480 ms

./adyen-salesforce-commerce-cloud/cartridges/int_adyen_overlay/copy:
  ./adyen-salesforce-commerce-cloud/cartridges/int_adyen_overlay/copy (webpack 5.75.0) compiled successfully in 477 ms

./adyen-salesforce-commerce-cloud/cartridges/bm_adyen/clean:
  ./adyen-salesforce-commerce-cloud/cartridges/bm_adyen/clean (webpack 5.75.0) compiled successfully in 474 ms

./adyen-salesforce-commerce-cloud/cartridges/bm_adyen/copy:
  ./adyen-salesforce-commerce-cloud/cartridges/bm_adyen/copy (webpack 5.75.0) compiled successfully in 471 ms
PS E:\GOC Projects\Commerce Cloud Projects\goc-task> `
