### ISSUE TITLE
Error while redirecting to order confirmation page when using non adyen payment

### ISSUE THREAD

**Issue by ig-pranav** [Adyen/adyen-salesforce-commerce-cloud#948]
**Describe the bug**
If there are multiple payment cartridge and if we try to place an order using non adyen payment service, the order confirmation page will not render due to the _IndexOutOfBoundsException_ in int_adyen_SFRA cartridge. Please see the below screenshot
<img width="683" alt="AdyenErrorPaypal" src="https://github.com/Adyen/adyen-salesforce-commerce-cloud/assets/87239818/4ffa3e6d-8186-4cf2-bb66-dd2fc6262f60">

**Below int_adyen_SFRA cartridge code is getting broken on _controllers/middlewares/order/confirm.js_ line no. 49**
<img width="521" alt="AdyenErrorPaypalCode" src="https://github.com/Adyen/adyen-salesforce-commerce-cloud/assets/87239818/7d113925-81b5-4969-a788-8004b44fd5f4">
`var paymentInstrument = order.getPaymentInstruments(AdyenHelper.getOrderMainPaymentInstrumentType(order))[0];`
Here **_AdyenHelper.getOrderMainPaymentInstrumentType(order)_** value is **AdyenComponent** by default. So the **order.getPaymentInstruments('AdyenComponent')** does not have a value since the order payment method is non adyen and here we are trying to call the first index [0] value of an empty array - Hence broken

**To Reproduce**
1. Go to checkout payment section
2. Place an order using non adyen payment
3. See error

**Expected behavior**
Should redirect to order confirmation page

**There should need a condition to check the length of the array in order to fix this issue**. see below
<img width="626" alt="Screenshot 2023-08-08 180731" src="https://github.com/Adyen/adyen-salesforce-commerce-cloud/assets/87239818/914f1c3b-e0a7-4728-8de1-9bd2bb92c1d4">

**Comment by amihajlovski** [comment]
Hi @ig-pranav 

Thanks for raising this, we will try to include it in the next patch release soon

Kind Regards
Aleksandar
Adyen

**Comment by ig-pranav** [comment]
Thanks @amihajlovski for the response.
Would you be able to give us an indication of when this would be available by?  This would help us plan our Adyen upgrade sprint accordingly.

**Comment by ig-pranav** [comment]
Thanks @amihajlovski for the response.
Would you be able to give us an indication of when this would be available by? This would help us plan our Adyen upgrade sprint accordingly.

**Comment by amihajlovski** [comment]
Hello @ig-pranav 

Can you confirm that the suggested condition check works for you so we can add it?
We aim to release it in two weeks from now.

Kind Regards
Aleksandar 
Adyen

**Comment by ig-pranav** [comment]
Hi @amihajlovski 
Thank you for your reply. 
That condition check logic worked for us perfectly. Please add it.

Thanks
Pranav

**Comment by amihajlovski** [comment]
Hello @ig-pranav 

The [following PR](https://github.com/Adyen/adyen-salesforce-commerce-cloud/pull/953) will be included in the next release. If possible please check it out within your cartridge and let us know if you find some other issues.

Kind Regards
Aleksandar 
Adyen

**Comment by ig-pranav** [comment]
Hello @amihajlovski 

We have checked it out within our cartridge and it is working Fine. No other issues found.

Can you please let us know when will be the next release? so that we can plan our Adyen sprint accordingly.

Thanks
Pranav

**Comment by amihajlovski** [comment]
Hello @ig-pranav 

We made a release today so you issue is fixed there 
https://github.com/Adyen/adyen-salesforce-commerce-cloud/releases/tag/23.2.1

Kind Regards
Aleksandar
Adyen
