### ISSUE TITLE
Cartridge can't be transpiled in production mode

### ISSUE THREAD

**Issue by igeorgiev-ewave** [Adyen/adyen-salesforce-commerce-cloud#956]
**Describe the bug**
If a build tool tries to transpile the cartridge with Node production mode active, the process fails because of these missing Babel dependencies:
* @babel/cli
* @babel/core
* @babel/plugin-transform-runtime
* @babel/plugin-proposal-class-properties
* @babel/plugin-proposal-decorators
* @babel/plugin-proposal-optional-chaining
* @babel/preset-env

They are not considered runtime dependencies by the package.json file, but the cartridge doesn't ship with code that is already transpiled. This requires transpiling the cartridge in production mode.

**To Reproduce**
1. Clone the main branch of this repo
2. Run `npm install --production=true`
3. Run `npm run transpile`
4. Code can't be transpiled due to missing Babel dependencies

**Expected behavior**
The `transpile` script is successful in Node production mode

**Desktop (please complete the following information):**
 - OS: Any
 - Browser Any
 - Version 23.2.0

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Any
 - Browser Any
 - Version 23.2.0

**Comment by shanikantsingh** [comment]
Hi @igeorgiev-ewave,
The main branch already contains the transpiled code under [cartridges](https://github.com/Adyen/adyen-salesforce-commerce-cloud/tree/main/cartridges) folder. 
You could do `npm install `without production mode flag and do `npm run uploadCartridge` to push cartridges to Sandbox.

**Comment by igeorgiev-ewave** [comment]
Hello @shanikantsingh !

I apologize for not noticing this sooner. The cartridges folder solves my problem.

Thank you for your help and quick response!
