### ISSUE TITLE
This endpoint for Additional Details Call is not implemented under Adyen.js Controller

### ISSUE THREAD

**Issue by atemel** [Adyen/adyen-salesforce-commerce-cloud#963]
https://github.com/Adyen/adyen-salesforce-commerce-cloud/blob/2e929de7856b83d5549c35dc9897b6d9a13d08b8/cartridges/int_adyen_overlay/cartridge/templates/default/threeds2/adyen3ds2.isml#L5C60-L5C73

**Comment by atemel** [comment]
When Dropin emit onAddtionalDetails call for 3ds2 cards, front end calling Adyen-Authorize3DS2 endpoint for details request but this endpoint is not implemented.

**Comment by amihajlovski** [comment]
Hello @atemel 

That file (adyen3ds2.isml) is not being used at all on that version and is removed in one of the later versions.
3DS2 flow works well on that version you are testing.

Kind Regards
Aleksandar
Adyen
