### ISSUE TITLE
Salesforce certification for SFRA?

### ISSUE THREAD

**Issue by ltomov** [Adyen/adyen-salesforce-commerce-cloud#97]
Hello,

Please excuse me if this is not the right place to ask this.

I see the SFRA version of the cartridge is under active development, do you know approximately when it is expected to reach a stable state? And do you plan to submit it to Salesforce for certification?

I'm asking because we're currently using it, however there are a few issues that we ended up fixing ourselves, yet I see in the recent commits Adyen has also fixed them. So I'm wondering if we should wait a while before merging the code?

Thank you!

**Comment by maassenbas** [comment]
Hi @ltomov ,

The release 18.2.1 is a certified and stable version of the SFRA cartridge. 
If you still see any other issues, please let us know, so we can take a look at it. 

Kind regards,
Bas Maassen
