### ISSUE TITLE
Unknown dynamic property 'adyen_payment_Adyen_Payment_Method'

### ISSUE THREAD

**Issue by mcauxmad** [Adyen/adyen-salesforce-commerce-cloud#983]
In version 23.3.0

ReferenceError: Unknown dynamic property 'adyen_payment_Adyen_Payment_Method' for class 'class dw.object.ExtensibleObject$ExtensibleObjectAttributes'. (int_adyen_SFRA/cartridge/scripts/hooks/payment/processor/middlewares/handle.js#20)

Correction : adyen_payment___Adyen_Payment_Method (with double underscore)

**Comment by amihajlovski** [comment]
Hello @mcauxmad 

We are aware of this issue and it is fixed in this PR #979 
It will be included in the next release

Kind Regards
Aleksandar
Adyen
