### ISSUE TITLE
Content type for apple domain verification file

### ISSUE THREAD

**Issue by nishad-ashraf** [Adyen/adyen-salesforce-commerce-cloud#993]
For apple pay domain verification, when the request from '/.well-known/apple-developer-merchantid-domain-association' is recieved , content type is not set in Adyen oob code in RedirectURL.js

![image](https://github.com/Adyen/adyen-salesforce-commerce-cloud/assets/42961626/345f0171-d65b-41c3-909c-75cd23650133)

In SFCC since the content type is always text/html as it not set in code to _Content-Type: text/plain_

**Comment by amihajlovski** [comment]
Hello @nishad-ashraf 

Closing this issue because its a duplicate one

Kind Regards
Aleksandar
Adyen
