### ISSUE TITLE
Wrong Custom Preference ID reference

### ISSUE THREAD

**Issue by renju-george** [Adyen/adyen-salesforce-commerce-cloud#994]
- In the system-objecttype-extensions.xml, the 2 attributes are named as "adyen_payment__Adyen_Payment_Method" and "adyen_payment__Adyen_Payment_Method_Variant"
- If you notice, both the variables have double underscores after "adyen_payment"
- But via code, this extra underscore is being missed in a couple of places, which leads to issues. 
- \cartridges\int_adyen_SFRA\cartridge\scripts\hooks\payment\processor\middlewares\handle.js 
- Line:20
- \src\cartridges\int_adyen_SFRA\cartridge\scripts\hooks\payment\processor\middlewares\handle.js 
- Line: 24
- 
![image](https://github.com/Adyen/adyen-salesforce-commerce-cloud/assets/61410720/a4d49de9-0b56-4c2f-b925-73e05076a5e2)

**Comment by amihajlovski** [comment]
Hello @renju-george 

We are aware of this issue and it is fixed in this PR https://github.com/Adyen/adyen-salesforce-commerce-cloud/pull/979
It will be included in the next release

Kind Regards
Aleksandar
Adyen
