### ISSUE TITLE
Applepay domain verification Failure for SFCC

### ISSUE THREAD

**Issue by nishad-ashraf** [Adyen/adyen-salesforce-commerce-cloud#995]
In Adyen SFRA v23.2.1 cartridge, for applepay domain verification, the applepay domain association file content has to be stored in site peference - **_Adyen_ApplePay_DomainAssociation_**
The applepay domain association file provided in the Adyen documentation (https://docs.adyen.com/plugins/salesforce-commerce-cloud/set-up-payment-methods/?tab=use_adyen_s_apple_pay_certificate_1#step-5-go-live-with-apple-pay) has a line ending with blank space/blank line

As per OOB Adyen cartridge code - print() function is used to render this domain association file content is sfcc and print() removes / trim the ending line ending. So the domain verification fails. 
On changing print() to println() the line endings are retained and executing cksum and xxd commands for website URL and comparing with https://eu.adyen.link/.well-known/apple-developer-merchantid-domain-association returns same cksum and xxd value 

Changes-
1. Replace print() with println()
2. Add code to set response header text/plain . This is mentioned in doc - https://eu.adyen.link/.well-known/apple-developer-merchantid-domain-association

`var server = require('server');
var URLRedirectMgr = require('dw/web/URLRedirectMgr');
var AdyenConfigs = require('*/cartridge/scripts/util/adyenConfigs');
var constants = require('../client/default/js/constants');
server.extend(module.superModule);
server.prepend('Start', function (req, res, next) {
  var origin = URLRedirectMgr.redirectOrigin;
  // Intercept the incoming path request
  if (origin.match(constants.APPLE_DOMAIN_URL)) {
    var applePayDomainAssociation = AdyenConfigs.getApplePayDomainAssociation();
    response.getWriter().print(applePayDomainAssociation);  
    return null;
  }
  return next();
});
module.exports = server.exports();`

Changed code -
`var server = require('server');
var URLRedirectMgr = require('dw/web/URLRedirectMgr');
var AdyenConfigs = require('*/cartridge/scripts/util/adyenConfigs');
var constants = require('../client/default/js/constants');
server.extend(module.superModule);
server.prepend('Start', function (req, res, next) {
  var origin = URLRedirectMgr.redirectOrigin;
  // Intercept the incoming path request
  if (origin.match(constants.APPLE_DOMAIN_URL)) {
    var applePayDomainAssociation = AdyenConfigs.getApplePayDomainAssociation();
    res.setHttpHeader(dw.system.Response.CONTENT_TYPE, 'text/plain');
    response.getWriter().println(applePayDomainAssociation);
    return null;
  }
  return next();
});
module.exports = server.exports();`

![image](https://github.com/Adyen/adyen-salesforce-commerce-cloud/assets/42961626/48c32ab7-f46e-4f8c-b6df-9ff8a55eb8a2)

File path: int_adyen_SFRA/cartridge/controllers/RedirectURL.js

Is it possible to fix this and provide a patch?

**Comment by zenit2001** [comment]
Hi @nishad-ashraf , 

We will set up an investigation internally regarding this and will keep you updated.

With kind regards,
Zenit
Adyen
